import { assertDistinct, dedupeLines } from "./guards";
import type { BusinessFacts, CopyKind, CopyLine, Lang, Niche } from "./types";

function nameOf(facts: BusinessFacts): string {
  return facts.name.value || facts.host;
}

interface Seed {
  kind: CopyKind;
  angle: string;
  ar: string;
  he: string;
  en: string;
  ctaAr: string;
  ctaHe: string;
  ctaEn: string;
  need?: "phone" | "place" | "hours" | "service";
}

function pick(facts: BusinessFacts, i: number) {
  return {
    name: nameOf(facts),
    place: facts.place.value,
    service: facts.services.length ? facts.services[i % facts.services.length] : null,
    phone: facts.phone.value,
    hours: facts.hours.value,
    wa: facts.whatsapp.value,
  };
}

function fill(template: string, facts: BusinessFacts, index: number): string {
  const p = pick(facts, index);
  return template
    .replaceAll("{name}", p.name)
    .replaceAll("{place}", p.place || "")
    .replaceAll("{service}", p.service || "")
    .replaceAll("{phone}", p.phone || "")
    .replaceAll("{hours}", p.hours || "")
    .replace(/\s{2,}/g, " ")
    .replace(/\s+([،,.!?])/g, "$1")
    .trim();
}

function commonSeeds(): Seed[] {
  return [
    {
      kind: "headline",
      angle: "name-place",
      need: "place",
      ar: "{name} في {place}",
      he: "{name} ב{place}",
      en: "{name} in {place}",
      ctaAr: "زور الصفحة",
      ctaHe: "בקרו בעמוד",
      ctaEn: "Visit the page",
    },
    {
      kind: "headline",
      angle: "name-only",
      ar: "هاي {name}",
      he: "זה {name}",
      en: "This is {name}",
      ctaAr: "ادخل شوف",
      ctaHe: "כנסו לראות",
      ctaEn: "Come see",
    },
    {
      kind: "headline",
      angle: "service-name",
      need: "service",
      ar: "{service} عند {name}",
      he: "{service} אצל {name}",
      en: "{service} at {name}",
      ctaAr: "شوف الخدمة",
      ctaHe: "ראו את השירות",
      ctaEn: "See the service",
    },
    {
      kind: "headline",
      angle: "near-you",
      need: "place",
      ar: "قريب عليك في {place}: {name}",
      he: "קרוב אליכם ב{place}: {name}",
      en: "Near you in {place}: {name}",
      ctaAr: "شوف وين",
      ctaHe: "בדקו איפה",
      ctaEn: "See where",
    },
    {
      kind: "headline",
      angle: "today",
      ar: "بدك تخلّصها اليوم مع {name}؟",
      he: "רוצים לסגור את זה היום עם {name}?",
      en: "Want this done today with {name}?",
      ctaAr: "يلا من الصفحة",
      ctaHe: "יאללה מהעמוד",
      ctaEn: "Go from the page",
    },
    {
      kind: "headline",
      angle: "first",
      ar: "أول زيارة لـ {name} — على مهلك",
      he: "ביקור ראשון אצל {name} — בנחת",
      en: "First visit to {name} — at your pace",
      ctaAr: "احجز من الصفحة",
      ctaHe: "קבעו מהעמוד",
      ctaEn: "Book from the page",
    },
    {
      kind: "headline",
      angle: "hours",
      need: "hours",
      ar: "{name} فاتح {hours}",
      he: "{name} פתוח {hours}",
      en: "{name} is open {hours}",
      ctaAr: "لحّق الدوام",
      ctaHe: "תספיקו לשעות",
      ctaEn: "Catch the hours",
    },
    {
      kind: "headline",
      angle: "question",
      ar: "وينك عن {name}؟",
      he: "איפה הייתם מ{name}?",
      en: "Where have you been — {name} is here",
      ctaAr: "تعالا شوف",
      ctaHe: "בואו תראו",
      ctaEn: "Come have a look",
    },
    {
      kind: "headline",
      angle: "family",
      need: "place",
      ar: "خد أهلك على {name} — {place}",
      he: "קחו את המשפחה ל{name} — {place}",
      en: "Bring the family to {name} — {place}",
      ctaAr: "احكي مع العيلة",
      ctaHe: "דברו בבית",
      ctaEn: "Talk at home",
    },
    {
      kind: "headline",
      angle: "usp-service",
      need: "service",
      ar: "إذا {service} همّك — {name} هون",
      he: "אם {service} רלוונטי — {name} כאן",
      en: "If {service} is what you need — {name} is here",
      ctaAr: "كمّل قراءة",
      ctaHe: "המשיכו לקרוא",
      ctaEn: "Keep reading",
    },
    {
      kind: "hook",
      angle: "pain",
      ar: "زهقت تدور؟ {name} قدامك.",
      he: "נמאס לחפש? {name} מולכם.",
      en: "Tired of hunting? {name} is right here.",
      ctaAr: "اسأل من الصفحة",
      ctaHe: "שאלו מהעמוד",
      ctaEn: "Ask on the page",
    },
    {
      kind: "hook",
      angle: "whatsapp",
      need: "phone",
      ar: "ابعت واتساب لـ {name}: {phone}",
      he: "שלחו וואטסאפ ל{name}: {phone}",
      en: "WhatsApp {name}: {phone}",
      ctaAr: "ابعت هسا",
      ctaHe: "שלחו עכשיו",
      ctaEn: "Message now",
    },
    {
      kind: "hook",
      angle: "neighbor",
      need: "place",
      ar: "جارك في {place} بمرّق على {name}.",
      he: "השכן ב{place} כבר מכיר את {name}.",
      en: "Your neighbor in {place} already knows {name}.",
      ctaAr: "اسأل عن المواعيد",
      ctaHe: "שאלו על תורים",
      ctaEn: "Ask about times",
    },
    {
      kind: "hook",
      angle: "who",
      need: "service",
      ar: "إذا بتدور {service} — صفحة {name} إلك.",
      he: "אם אתם מחפשים {service} — העמוד של {name} בשבילכם.",
      en: "Looking for {service}? {name}’s page is for you.",
      ctaAr: "اختار الخدمة",
      ctaHe: "בחרו שירות",
      ctaEn: "Pick a service",
    },
    {
      kind: "hook",
      angle: "week",
      need: "place",
      ar: "هالأسبوع فيك تمرّ على {name} في {place}.",
      he: "השבוע אפשר לעבור ב{name} ב{place}.",
      en: "This week you can stop by {name} in {place}.",
      ctaAr: "خطّط الزيارة",
      ctaHe: "תכננו ביקור",
      ctaEn: "Plan a visit",
    },
    {
      kind: "hook",
      angle: "hours-hook",
      need: "hours",
      ar: "دوام {name}: {hours}.",
      he: "שעות {name}: {hours}.",
      en: "{name} hours: {hours}.",
      ctaAr: "راجع الدوام",
      ctaHe: "בדקו שעות",
      ctaEn: "Check hours",
    },
    {
      kind: "hook",
      angle: "scroll",
      need: "place",
      ar: "وقّف السكرول: {name} في {place}.",
      he: "עצרו את הגלילה: {name} ב{place}.",
      en: "Stop the scroll: {name} in {place}.",
      ctaAr: "كمّل للإعلان",
      ctaHe: "המשיכו למודעה",
      ctaEn: "Continue to the ad",
    },
    {
      kind: "hook",
      angle: "call-easy",
      need: "phone",
      ar: "اتّصل على {phone} واسأل {name}.",
      he: "התקשרו ל{phone} ושאלו את {name}.",
      en: "Call {phone} and ask {name}.",
      ctaAr: "اتّصل هسا",
      ctaHe: "התקשרו עכשיו",
      ctaEn: "Call now",
    },
  ];
}

function nicheSeeds(niche: Niche): Seed[] {
  const extra: Record<Niche, Seed[]> = {
    clinic: [
      {
        kind: "headline",
        angle: "calm-clinic",
        need: "place",
        ar: "عيادة هادية في {place}: {name}",
        he: "מרפאה רגועה ב{place}: {name}",
        en: "A calmer clinic in {place}: {name}",
        ctaAr: "شوف العيادة",
        ctaHe: "ראו את המרפאה",
        ctaEn: "See the clinic",
      },
      {
        kind: "hook",
        angle: "clinic-pain",
        need: "service",
        ar: "موجوع؟ {name} ذاكر {service}.",
        he: "כואב? {name} מציין {service}.",
        en: "Hurting? {name} lists {service}.",
        ctaAr: "اقرأ العلاج",
        ctaHe: "קראו את הטיפול",
        ctaEn: "Read the care",
      },
      {
        kind: "cta",
        angle: "book",
        ar: "احجز موعدك من صفحة {name}",
        he: "קבעו תור מעמוד {name}",
        en: "Book from {name}’s page",
        ctaAr: "احجز موعد",
        ctaHe: "קבעו תור",
        ctaEn: "Book a visit",
      },
      {
        kind: "cta",
        angle: "call",
        need: "phone",
        ar: "اتّصل {phone} واسأل أقرب وقت",
        he: "התקשרו {phone} לשעה פנויה",
        en: "Call {phone} for the next opening",
        ctaAr: "اتّصل للموعد",
        ctaHe: "התקשרו לתור",
        ctaEn: "Call for a slot",
      },
      {
        kind: "cta",
        angle: "consult",
        ar: "اطلب استشارة من {name}",
        he: "בקשו ייעוץ מ{name}",
        en: "Ask {name} for a consult",
        ctaAr: "اطلب استشارة",
        ctaHe: "בקשו ייעוץ",
        ctaEn: "Request a consult",
      },
      {
        kind: "cta",
        angle: "map",
        need: "place",
        ar: "افتح الخريطة لـ {name} في {place}",
        he: "פתחו מפה ל{name} ב{place}",
        en: "Open the map for {name} in {place}",
        ctaAr: "افتح الخريطة",
        ctaHe: "פתחו מפה",
        ctaEn: "Open the map",
      },
      {
        kind: "cta",
        angle: "wa",
        need: "phone",
        ar: "واتساب العيادة {phone}",
        he: "וואטסאפ למרפאה {phone}",
        en: "WhatsApp the clinic {phone}",
        ctaAr: "واتساب العيادة",
        ctaHe: "וואטסאפ למרפאה",
        ctaEn: "WhatsApp clinic",
      },
      {
        kind: "cta",
        angle: "ask-service",
        need: "service",
        ar: "اسأل عن {service} قبل ما تقرّر",
        he: "שאלו על {service} לפני שמחליטים",
        en: "Ask about {service} before you decide",
        ctaAr: "اسأل قبل القرار",
        ctaHe: "שאלו קודם",
        ctaEn: "Ask first",
      },
    ],
    tutoring: [
      {
        kind: "headline",
        angle: "pace",
        need: "service",
        ar: "شرح {service} على مهلك — {name}",
        he: "הסבר {service} בקצב שלכם — {name}",
        en: "{service} at your pace — {name}",
        ctaAr: "شوف أسلوبهم",
        ctaHe: "ראו סגנון",
        ctaEn: "See their style",
      },
      {
        kind: "hook",
        angle: "exam",
        need: "service",
        ar: "قبل الامتحان: {service} مع {name}.",
        he: "לפני המבחן: {service} עם {name}.",
        en: "Before the exam: {service} with {name}.",
        ctaAr: "رتّب الحصة",
        ctaHe: "סדרו שיעור",
        ctaEn: "Set the lesson",
      },
      {
        kind: "cta",
        angle: "book",
        ar: "احجز حصة من صفحة {name}",
        he: "קבעו שיעור בעמוד {name}",
        en: "Book a lesson on {name}’s page",
        ctaAr: "احجز حصة",
        ctaHe: "קבעו שיעור",
        ctaEn: "Book a lesson",
      },
      {
        kind: "cta",
        angle: "call",
        need: "phone",
        ar: "اتّصل {phone} واسأل عن الحصص",
        he: "התקשרו {phone} על שיעורים",
        en: "Call {phone} about lessons",
        ctaAr: "اسأل عن الحصص",
        ctaHe: "שאלו על שיעורים",
        ctaEn: "Ask about lessons",
      },
      {
        kind: "cta",
        angle: "plan",
        ar: "اطلب خطة أسبوع من {name}",
        he: "בקשו תוכנית שבוע מ{name}",
        en: "Ask {name} for a weekly plan",
        ctaAr: "اطلب الخطة",
        ctaHe: "בקשו תוכנית",
        ctaEn: "Ask for a plan",
      },
      {
        kind: "cta",
        angle: "map",
        need: "place",
        ar: "العنوان في {place}",
        he: "הכתובת ב{place}",
        en: "The address in {place}",
        ctaAr: "خد الاتجاه",
        ctaHe: "קחו ניווט",
        ctaEn: "Get directions",
      },
      {
        kind: "cta",
        angle: "wa",
        need: "phone",
        ar: "واتساب المدرس {phone}",
        he: "וואטסאפ למורה {phone}",
        en: "WhatsApp the tutor {phone}",
        ctaAr: "واتساب الدرس",
        ctaHe: "וואטסאפ לשיעור",
        ctaEn: "WhatsApp tutor",
      },
      {
        kind: "cta",
        angle: "subject",
        need: "service",
        ar: "ابعِت إنك بدك {service}",
        he: "כתבו שאתם צריכים {service}",
        en: "Write that you need {service}",
        ctaAr: "ابعت المادة",
        ctaHe: "שלחו מקצוע",
        ctaEn: "Send the subject",
      },
    ],
    restaurant: [
      {
        kind: "headline",
        angle: "table",
        ar: "طاولة لسا فاضية عند {name}",
        he: "עדיין יש שולחן אצל {name}",
        en: "A table still open at {name}",
        ctaAr: "احجز قبل ما تطلع",
        ctaHe: "הזמינו לפני היציאה",
        ctaEn: "Reserve before you go",
      },
      {
        kind: "hook",
        angle: "craving",
        need: "service",
        ar: "جاعان على {service}؟ {name} بيستناك.",
        he: "בא לכם {service}? {name} מחכה.",
        en: "Craving {service}? {name} is waiting.",
        ctaAr: "اطلب من الصفحة",
        ctaHe: "הזמינו מהעמוד",
        ctaEn: "Order from the page",
      },
      {
        kind: "cta",
        angle: "book",
        ar: "احجز طاولة عند {name}",
        he: "הזמינו שולחן אצל {name}",
        en: "Reserve a table at {name}",
        ctaAr: "احجز طاولة",
        ctaHe: "הזמינו שולחן",
        ctaEn: "Reserve a table",
      },
      {
        kind: "cta",
        angle: "call",
        need: "phone",
        ar: "اتّصل {phone} واسأل شو فاتح",
        he: "התקשרו {phone} מה פתוח",
        en: "Call {phone} and ask what’s open",
        ctaAr: "اسأل الدوام",
        ctaHe: "שאלו שעות",
        ctaEn: "Ask the hours",
      },
      {
        kind: "cta",
        angle: "menu",
        need: "service",
        ar: "شوف {service} عند {name}",
        he: "ראו {service} אצל {name}",
        en: "See {service} at {name}",
        ctaAr: "شوف القائمة",
        ctaHe: "ראו תפריט",
        ctaEn: "See the menu",
      },
      {
        kind: "cta",
        angle: "map",
        need: "place",
        ar: "اتجه على {name} في {place}",
        he: "נווטו ל{name} ב{place}",
        en: "Head to {name} in {place}",
        ctaAr: "خذني هناك",
        ctaHe: "קחו אותי לשם",
        ctaEn: "Take me there",
      },
      {
        kind: "cta",
        angle: "wa",
        need: "phone",
        ar: "واتساب المطعم {phone}",
        he: "וואטסאפ למקום {phone}",
        en: "WhatsApp {name} {phone}",
        ctaAr: "اطلب بالواتساب",
        ctaHe: "הזמינו בוואטסאפ",
        ctaEn: "Order on WhatsApp",
      },
      {
        kind: "cta",
        angle: "tonight",
        need: "place",
        ar: "مرّ الليلة إذا كنت بـ {place}",
        he: "עברו הערב אם אתם ב{place}",
        en: "Stop by tonight if you’re in {place}",
        ctaAr: "مرّ الليلة",
        ctaHe: "עברו הערב",
        ctaEn: "Stop by tonight",
      },
    ],
    renovation: [
      {
        kind: "headline",
        angle: "home",
        need: "place",
        ar: "بيت في {place} عم يتجدّد مع {name}",
        he: "בית ב{place} מתחדש עם {name}",
        en: "A home in {place} refreshing with {name}",
        ctaAr: "شوف شغلهم",
        ctaHe: "ראו את העבודה",
        ctaEn: "See the work",
      },
      {
        kind: "hook",
        angle: "wall",
        need: "service",
        ar: "الحيط بده {service}؟ اسأل {name}.",
        he: "הקיר צריך {service}? שאלו את {name}.",
        en: "Need {service} on the wall? Ask {name}.",
        ctaAr: "اسأل المقاول",
        ctaHe: "שאלו את הקבלן",
        ctaEn: "Ask the contractor",
      },
      {
        kind: "cta",
        angle: "book",
        ar: "اطلب كشف بيت من {name}",
        he: "בקשו ביקור בית מ{name}",
        en: "Request a house visit from {name}",
        ctaAr: "اطلب كشف",
        ctaHe: "בקשו ביקור",
        ctaEn: "Request a visit",
      },
      {
        kind: "cta",
        angle: "call",
        need: "phone",
        ar: "اتّصل {phone} ووصف الشغل",
        he: "התקשרו {phone} ותארו את העבודה",
        en: "Call {phone} and describe the job",
        ctaAr: "وصف الشغل",
        ctaHe: "תארו עבודה",
        ctaEn: "Describe the job",
      },
      {
        kind: "cta",
        angle: "photos",
        ar: "ابعِت صور الزاوية لـ {name}",
        he: "שלחו תמונות לפינה ל{name}",
        en: "Send room photos to {name}",
        ctaAr: "ابعت صور",
        ctaHe: "שלחו תמונות",
        ctaEn: "Send photos",
      },
      {
        kind: "cta",
        angle: "map",
        need: "place",
        ar: "المقاول في {place}: {name}",
        he: "הקבלן ב{place}: {name}",
        en: "The contractor in {place}: {name}",
        ctaAr: "حدد المنطقة",
        ctaHe: "סמנו אזור",
        ctaEn: "Mark the area",
      },
      {
        kind: "cta",
        angle: "wa",
        need: "phone",
        ar: "واتساب المقاول {phone}",
        he: "וואטסאפ לקבלן {phone}",
        en: "WhatsApp the contractor {phone}",
        ctaAr: "واتساب المقاول",
        ctaHe: "וואטסאפ לקבלן",
        ctaEn: "WhatsApp contractor",
      },
      {
        kind: "cta",
        angle: "scope",
        need: "service",
        ar: "أكّد إذا بعملوا {service}",
        he: "אשרו אם הם עושים {service}",
        en: "Confirm they do {service}",
        ctaAr: "أكّد الخدمة",
        ctaHe: "אשרו שירות",
        ctaEn: "Confirm the service",
      },
    ],
    fitness: [
      {
        kind: "headline",
        angle: "boutique",
        need: "place",
        ar: "ستوديو صغير في {place}: {name}",
        he: "סטודיו קטן ב{place}: {name}",
        en: "A small studio in {place}: {name}",
        ctaAr: "شوف الحصص",
        ctaHe: "ראו שיעורים",
        ctaEn: "See classes",
      },
      {
        kind: "hook",
        angle: "breath",
        need: "service",
        ar: "بدك تتنفس شوي؟ {service} عند {name}.",
        he: "צריכים לנשום? {service} אצל {name}.",
        en: "Need a breath? {service} at {name}.",
        ctaAr: "ادخل الجدول",
        ctaHe: "כנסו למערכת",
        ctaEn: "Open the schedule",
      },
      {
        kind: "cta",
        angle: "book",
        ar: "احجز حصة عند {name}",
        he: "קבעו שיעור אצל {name}",
        en: "Book a class at {name}",
        ctaAr: "احجز حصة",
        ctaHe: "קבעו שיעור",
        ctaEn: "Book a class",
      },
      {
        kind: "cta",
        angle: "call",
        need: "phone",
        ar: "اتّصل {phone} واسأل الجدول",
        he: "התקשרו {phone} למערכת",
        en: "Call {phone} for the timetable",
        ctaAr: "اسأل الجدول",
        ctaHe: "שאלו מערכת",
        ctaEn: "Ask the timetable",
      },
      {
        kind: "cta",
        angle: "trial",
        ar: "جرّب حصة أولى مع {name}",
        he: "נסו שיעור ראשון עם {name}",
        en: "Try a first class with {name}",
        ctaAr: "جرّب حصة",
        ctaHe: "נסו שיעור",
        ctaEn: "Try a class",
      },
      {
        kind: "cta",
        angle: "map",
        need: "place",
        ar: "الاستوديو في {place}",
        he: "הסטודיו ב{place}",
        en: "The studio is in {place}",
        ctaAr: "خذ الاتجاه",
        ctaHe: "קחו ניווט",
        ctaEn: "Get directions",
      },
      {
        kind: "cta",
        angle: "wa",
        need: "phone",
        ar: "واتساب الاستوديو {phone}",
        he: "וואטסאפ לסטודיו {phone}",
        en: "WhatsApp the studio {phone}",
        ctaAr: "واتساب الحصة",
        ctaHe: "וואטסאפ לשיעור",
        ctaEn: "WhatsApp the class",
      },
      {
        kind: "cta",
        angle: "mat",
        need: "service",
        ar: "احجز مات لـ {service}",
        he: "שמרו מזרן ל{service}",
        en: "Hold a mat for {service}",
        ctaAr: "احجز مات",
        ctaHe: "שמרו מזרן",
        ctaEn: "Hold a mat",
      },
    ],
    out_of_niche: [
      {
        kind: "headline",
        angle: "generic",
        need: "place",
        ar: "{name} في {place}",
        he: "{name} ב{place}",
        en: "{name} in {place}",
        ctaAr: "افتح الصفحة",
        ctaHe: "פתחו עמוד",
        ctaEn: "Open the page",
      },
      {
        kind: "hook",
        angle: "soft-out",
        ar: "{name}: اللي ظاهر على صفحتهم، وبس.",
        he: "{name}: רק מה שכתוב אצלם.",
        en: "{name}: only what their page shows.",
        ctaAr: "اقرأ الصفحة",
        ctaHe: "קראו את העמוד",
        ctaEn: "Read the page",
      },
      {
        kind: "cta",
        angle: "book",
        ar: "تواصل مع {name} من موقعهم",
        he: "צרו קשר עם {name} מהאתר",
        en: "Contact {name} from their site",
        ctaAr: "تواصل من الموقع",
        ctaHe: "צרו קשר",
        ctaEn: "Get in touch",
      },
      {
        kind: "cta",
        angle: "call",
        need: "phone",
        ar: "اتّصل {phone}",
        he: "התקשרו {phone}",
        en: "Call {phone}",
        ctaAr: "اتّصل",
        ctaHe: "התקשרו",
        ctaEn: "Call",
      },
      {
        kind: "cta",
        angle: "read",
        ar: "اقرأ وصف {name}",
        he: "קראו את התיאור של {name}",
        en: "Read {name}’s description",
        ctaAr: "اقرأ الوصف",
        ctaHe: "קראו תיאור",
        ctaEn: "Read the description",
      },
      {
        kind: "cta",
        angle: "map",
        need: "place",
        ar: "دور على {name} في {place}",
        he: "חפשו את {name} ב{place}",
        en: "Find {name} in {place}",
        ctaAr: "ابحث بالمكان",
        ctaHe: "חפשו במקום",
        ctaEn: "Search the place",
      },
      {
        kind: "cta",
        angle: "wa",
        need: "phone",
        ar: "راسل {name} على {phone}",
        he: "כתבו ל{name} ב{phone}",
        en: "Message {name} at {phone}",
        ctaAr: "راسل المحل",
        ctaHe: "כתבו לעסק",
        ctaEn: "Message the business",
      },
      {
        kind: "cta",
        angle: "site",
        ar: "ارجع لرابط {name}",
        he: "חזרו לקישור של {name}",
        en: "Return to {name}’s link",
        ctaAr: "افتح الرابط",
        ctaHe: "פתחו קישור",
        ctaEn: "Open the link",
      },
    ],
  };
  return extra[niche];
}

function hasNeed(facts: BusinessFacts, need?: Seed["need"]): boolean {
  if (!need) return true;
  if (need === "phone") return Boolean(facts.phone.value);
  if (need === "place") return Boolean(facts.place.value);
  if (need === "hours") return Boolean(facts.hours.value);
  if (need === "service") return facts.services.length > 0;
  return true;
}

const FALLBACK_NO_NEED: Seed[] = [
  {
    kind: "headline",
    angle: "open-page",
    ar: "صفحة {name} جاهزة إلك",
    he: "העמוד של {name} מוכן לכם",
    en: "{name}’s page is ready for you",
    ctaAr: "افتح هسا",
    ctaHe: "פתחו עכשיו",
    ctaEn: "Open now",
  },
  {
    kind: "hook",
    angle: "direct",
    ar: "بلا فورم تيه: روح على {name}.",
    he: "בלי טפסים: לכו ל{name}.",
    en: "No scavenger form: go to {name}.",
    ctaAr: "روح للصفحة",
    ctaHe: "לעמוד",
    ctaEn: "Go to the page",
  },
  {
    kind: "cta",
    angle: "visit-site",
    ar: "زور موقع {name}",
    he: "בקרו באתר של {name}",
    en: "Visit {name}’s site",
    ctaAr: "زور الموقع",
    ctaHe: "בקרו באתר",
    ctaEn: "Visit the site",
  },
  {
    kind: "headline",
    angle: "host-name",
    ar: "{name}",
    he: "{name}",
    en: "{name}",
    ctaAr: "اقرأ المزيد",
    ctaHe: "קראו עוד",
    ctaEn: "Read more",
  },
  {
    kind: "hook",
    angle: "simple",
    ar: "{name} — خطوة وحدة من الرابط.",
    he: "{name} — צעד אחד מהקישור.",
    en: "{name} — one step from the link.",
    ctaAr: "خذ الخطوة",
    ctaHe: "עשו את הצעד",
    ctaEn: "Take the step",
  },
  {
    kind: "cta",
    angle: "save",
    ar: "احفظ صفحة {name} لبعدين",
    he: "שמרו את העמוד של {name}",
    en: "Save {name}’s page for later",
    ctaAr: "احفظ الصفحة",
    ctaHe: "שמרו עמוד",
    ctaEn: "Save the page",
  },
  {
    kind: "headline",
    angle: "ready",
    ar: "{name} جاهز يسمعك",
    he: "{name} מוכן לשמוע",
    en: "{name} is ready to hear you",
    ctaAr: "احكي هسا",
    ctaHe: "דברו עכשיו",
    ctaEn: "Talk now",
  },
  {
    kind: "headline",
    angle: "one-step",
    ar: "خطوة وحدة توصلّك لـ {name}",
    he: "צעד אחד אל {name}",
    en: "One step to {name}",
    ctaAr: "خذ الخطوة",
    ctaHe: "צעד",
    ctaEn: "Take a step",
  },
  {
    kind: "hook",
    angle: "no-form",
    ar: "ما في لف ودوران — {name} من الرابط.",
    he: "בלי סיבובים — {name} מהקישור.",
    en: "No runaround — {name} from the link.",
    ctaAr: "كمّل الرابط",
    ctaHe: "המשיכו בקישור",
    ctaEn: "Follow the link",
  },
  {
    kind: "hook",
    angle: "clear",
    ar: "الاسم واضح: {name}.",
    he: "השם ברור: {name}.",
    en: "The name is clear: {name}.",
    ctaAr: "تأكّد من الاسم",
    ctaHe: "וודאו שם",
    ctaEn: "Confirm the name",
  },
  {
    kind: "cta",
    angle: "write",
    ar: "اكتبلهم كلمة على صفحة {name}",
    he: "כתבו מילה בעמוד של {name}",
    en: "Leave a note on {name}’s page",
    ctaAr: "اكتب كلمة",
    ctaHe: "כתבו מילה",
    ctaEn: "Write a note",
  },
  {
    kind: "cta",
    angle: "open-now",
    ar: "افتح {name} بهاللحظة",
    he: "פתחו את {name} ברגע זה",
    en: "Open {name} this moment",
    ctaAr: "افتح هاللحظة",
    ctaHe: "פתחו ברגע",
    ctaEn: "Open this moment",
  },
];

export function buildCopyLines(facts: BusinessFacts, lang: Lang): CopyLine[] {
  const seeds = [...commonSeeds(), ...nicheSeeds(facts.niche), ...FALLBACK_NO_NEED];
  const lines: CopyLine[] = [];
  seeds.forEach((seed, index) => {
    if (!hasNeed(facts, seed.need)) return;
    const raw = lang === "he" ? seed.he : lang === "en" ? seed.en : seed.ar;
    const ctaRaw = lang === "he" ? seed.ctaHe : lang === "en" ? seed.ctaEn : seed.ctaAr;
    const text = fill(raw, facts, index);
    const ctaLabel = fill(ctaRaw, facts, index);
    if (!text || !ctaLabel) return;
    lines.push({
      id: `${seed.kind}-${seed.angle}`,
      kind: seed.kind,
      text,
      angle: seed.angle,
      ctaLabel,
    });
  });

  const unique = dedupeLines(lines);
  if (unique.length < 20) {
    const name = nameOf(facts);
    const extras: CopyLine[] = [
      { id: "extra-hello", kind: "headline", angle: "hello", text: lang === "ar" ? `مرحبا في ${name}` : lang === "he" ? `ברוכים הבאים ל${name}` : `Welcome to ${name}`, ctaLabel: lang === "ar" ? "أهلاً" : lang === "he" ? "שלום" : "Hello" },
      { id: "extra-more", kind: "hook", angle: "more", text: lang === "ar" ? `في تفاصيل زيادة عن ${name} على الصفحة.` : lang === "he" ? `יש עוד פרטים על ${name} בעמוד.` : `More about ${name} is on the page.`, ctaLabel: lang === "ar" ? "زِد قراءة" : lang === "he" ? "קראו עוד קצת" : "Read a bit more" },
      { id: "extra-go", kind: "cta", angle: "go", text: lang === "ar" ? `كمّل لصفحة ${name}` : lang === "he" ? `המשיכו לעמוד ${name}` : `Continue to ${name}`, ctaLabel: lang === "ar" ? "كمّل" : lang === "he" ? "המשיכו" : "Continue" },
      { id: "extra-ask", kind: "cta", angle: "ask-page", text: lang === "ar" ? `اسأل ${name} سؤال واحد` : lang === "he" ? `שאלו את ${name} שאלה אחת` : `Ask ${name} one question`, ctaLabel: lang === "ar" ? "اسأل سؤال" : lang === "he" ? "שאלו שאלה" : "Ask one question" },
    ];
    for (const extra of extras) {
      if (unique.length >= 24) break;
      if (unique.some((l) => l.text === extra.text)) continue;
      unique.push(extra);
    }
  }
  return unique;
}

export { assertDistinct };
