import type { BusinessFacts, Lang, Niche, NicheImage } from "./types";

interface Stock {
  id: string;
  src: string;
  theme: string;
}

const STOCK: Record<Niche, Stock[]> = {
  clinic: [
    { id: "c1", src: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=900&q=80", theme: "reception" },
    { id: "c2", src: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=900&q=80", theme: "chair" },
    { id: "c3", src: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&q=80", theme: "tools" },
    { id: "c4", src: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&q=80", theme: "hallway" },
    { id: "c5", src: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80", theme: "care" },
    { id: "c6", src: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=900&q=80", theme: "team" },
    { id: "c7", src: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=900&q=80", theme: "consult" },
    { id: "c8", src: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=900&q=80", theme: "calm" },
    { id: "c9", src: "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=900&q=80", theme: "light" },
  ],
  tutoring: [
    { id: "t1", src: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=900&q=80", theme: "desk" },
    { id: "t2", src: "https://images.unsplash.com/photo-1456513080880-7d93d20b90ff?w=900&q=80", theme: "books" },
    { id: "t3", src: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=900&q=80", theme: "classroom" },
    { id: "t4", src: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=900&q=80", theme: "notes" },
    { id: "t5", src: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=900&q=80", theme: "board" },
    { id: "t6", src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=900&q=80", theme: "pair" },
    { id: "t7", src: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=900&q=80", theme: "write" },
    { id: "t8", src: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=900&q=80", theme: "lecture" },
    { id: "t9", src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80", theme: "plan" },
  ],
  restaurant: [
    { id: "r1", src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=80", theme: "room" },
    { id: "r2", src: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80", theme: "coffee" },
    { id: "r3", src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80", theme: "plated" },
    { id: "r4", src: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80", theme: "table" },
    { id: "r5", src: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=900&q=80", theme: "street" },
    { id: "r6", src: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=80", theme: "dish" },
    { id: "r7", src: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=900&q=80", theme: "cafe" },
    { id: "r8", src: "https://images.unsplash.com/photo-1481833761820-0509d3217039?w=900&q=80", theme: "pastry" },
    { id: "r9", src: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=900&q=80", theme: "evening" },
  ],
  renovation: [
    { id: "n1", src: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&q=80", theme: "site" },
    { id: "n2", src: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80", theme: "kitchen" },
    { id: "n3", src: "https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=900&q=80", theme: "tools" },
    { id: "n4", src: "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=900&q=80", theme: "paint" },
    { id: "n5", src: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900&q=80", theme: "build" },
    { id: "n6", src: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=900&q=80", theme: "interior" },
    { id: "n7", src: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&q=80", theme: "crew" },
    { id: "n8", src: "https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=900&q=80", theme: "home" },
    { id: "n9", src: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80", theme: "space" },
  ],
  fitness: [
    { id: "f1", src: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80", theme: "gym" },
    { id: "f2", src: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=900&q=80", theme: "yoga" },
    { id: "f3", src: "https://images.unsplash.com/photo-1518611012118-696072451274?w=900&q=80", theme: "mat" },
    { id: "f4", src: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=900&q=80", theme: "coach" },
    { id: "f5", src: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=900&q=80", theme: "weights" },
    { id: "f6", src: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=900&q=80", theme: "studio" },
    { id: "f7", src: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=900&q=80", theme: "stretch" },
    { id: "f8", src: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=900&q=80", theme: "group" },
    { id: "f9", src: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=900&q=80", theme: "run" },
  ],
  out_of_niche: [
    { id: "o1", src: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80", theme: "desk" },
    { id: "o2", src: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=900&q=80", theme: "street" },
    { id: "o3", src: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=900&q=80", theme: "work" },
    { id: "o4", src: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=900&q=80", theme: "people" },
    { id: "o5", src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80", theme: "plan" },
    { id: "o6", src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=80", theme: "screen" },
    { id: "o7", src: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=900&q=80", theme: "office" },
    { id: "o8", src: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=900&q=80", theme: "room" },
    { id: "o9", src: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80", theme: "shop" },
  ],
};

function captionFor(stock: Stock, facts: BusinessFacts, lang: Lang, index: number): string {
  const name = facts.name.value || facts.host;
  const place = facts.place.value;
  const service = facts.services[index % Math.max(facts.services.length, 1)] || null;

  const packs: Record<Lang, Record<string, string[]>> = {
    ar: {
      reception: [`${name} — مدخل هادي من الموقع`, "جلسة أولى بلا لف ودوران"],
      chair: [service ? `${name}: ${service} مذكور عندهم` : `${name} — كرسي العلاج`],
      tools: ["تفاصيل الشغل من صفحة العيادة", `${name} — أدوات الظاهرة بالموقع`],
      hallway: [place ? `ممر العيادة — ${place}` : "ممر العيادة كما يظهر بالموقع"],
      care: ["رعاية مكتوبة، مش شعارات فاضي"],
      team: [`فريق ${name} — من الاسم الظاهر`],
      consult: ["استشارة من الصفحة، بدون اختراع سعر"],
      calm: [place ? `هدوء الجلسة في ${place}` : "هدوء الجلسة — من روح الموقع"],
      light: [`ضوء طبيعي لإعلان ${name}`],
      desk: [service ? `درس ${service} مع ${name}` : `مكتب الدرس — ${name}`],
      books: ["كتب الطاولة — مش مخزّن عام بلا عنوان"],
      classroom: [place ? `حصة قريبة من ${place}` : "حصة واضحة من وصف المركز"],
      notes: ["دفاتر التحضير — زاوية المذاكرة"],
      board: [`لوح ${name}`],
      pair: ["حصة ثنائية من طبيعة الدرس"],
      write: ["لحظة كتابة الحل"],
      lecture: [place ? `شرح في ${place}` : "شرح قدام اللوح"],
      plan: ["خطة أسبوع من الموجود بالموقع"],
      room: [place ? `صالة ${name} في ${place}` : `صالة ${name}`],
      coffee: ["فنجان الصبح — من هوية المقهى"],
      plated: [service ? `طبق ${service}` : "طبق اليوم من روح القائمة"],
      table: ["طاولة لاثنين — دعوة للجلوس"],
      street: [place ? `واجهة المحل في ${place}` : "واجهة المحل"],
      dish: [service ? `${service} كما نحكي عنه بدون سعر مخترع` : "طبق جاهز للتصوير"],
      cafe: [`ركن القهوة في ${name}`],
      pastry: ["حلويات الواجهة"],
      evening: ["سهرة خفيفة — إضاءة المساء"],
      site: [place ? `ورشة في ${place}` : `ورشة ${name}`],
      kitchen: [service ? `شغل ${service}` : "مطبخ بعد التشطيب — ستوك مجال"],
      build: ["عظم الشغل، مش وعود ROAS"],
      paint: [service ? `${service} — فرشاة على الحيط` : "دهان الحيطان"],
      interior: [`داخل بيت عميل ${name} (ستوك مجال)`],
      crew: ["طاقم المقاولة — صورة مجال"],
      home: ["بيت عم يتجدّد"],
      space: ["مساحة فاضية قبل الفرش"],
      gym: [`بساط ${name}`],
      yoga: [service ? `حصة ${service}` : "حصة يوغا بوتيك"],
      mat: ["مات على الخشب — ستوديو صغير"],
      coach: ["مدرب قريب، مش إعلان سلسلة"],
      weights: ["حديد الخفيف للبوتيك"],
      studio: [place ? `ستوديو في ${place}` : `ستوديو ${name}`],
      stretch: ["تمسيد قبل الحصة"],
      group: ["مجموعة صغيرة"],
      run: ["خطوة برّا — نفس الاسم"],
      work: [`مكتب ${name} — صورة عامة لأن التخصص برّا القائمة`],
      people: [`ناس ${name}`],
      screen: ["شاشة شغل عامة"],
      office: ["مكتب نهاري"],
      shop: ["إضاءة محل عامة"],
    },
    he: {
      reception: [`${name} — לובי שקט`],
      chair: [service ? `${name}: ${service}` : `כיסא הטיפול של ${name}`],
      tools: ["פרטים מהאתר, בלי מחיר מומצא"],
      hallway: [place ? `מסדרון ב${place}` : "מסדרון המרפאה"],
      care: ["טיפול כמו שכתוב באתר"],
      team: [`הצוות של ${name}`],
      consult: ["ייעוץ ראשון — בלי הבטחות ROAS"],
      calm: ["אווירה רגועה"],
      light: ["אור רך לקריאייטיב"],
      desk: [service ? `שיעור ${service}` : `שולחן הלמידה של ${name}`],
      books: ["ספרים על השולחן"],
      classroom: [place ? `שיעור ליד ${place}` : "כיתה קטנה"],
      notes: ["מחברת תרגול"],
      board: [`הלוח של ${name}`],
      pair: ["שיעור זוגי"],
      write: ["רגע כתיבה"],
      lecture: ["הסבר מול הלוח"],
      plan: ["תוכנית שבועית מהאתר"],
      room: [place ? `${name} ב${place}` : `חלל ${name}`],
      coffee: ["הקפה של הבוקר"],
      plated: [service ? `מנה: ${service}` : "מנה מהתפריט"],
      table: ["שולחן לשניים"],
      street: [place ? `חזית ב${place}` : "חזית העסק"],
      dish: ["מנה לצילום מודעה"],
      cafe: [`פינת הקפה ב${name}`],
      pastry: ["חלת הוויטרינה"],
      evening: ["תאורת ערב"],
      site: [place ? `אתר עבודה ב${place}` : `העבודה של ${name}`],
      kitchen: [service ? `עבודת ${service}` : "מטבח אחרי שיפוץ"],
      build: ["עבודה אמיתית, בלי הבטחות"],
      paint: ["צביעת קירות"],
      interior: ["פנים הבית"],
      crew: ["צוות השיפוץ"],
      home: ["בית מתחדש"],
      space: ["חלל לפני ריהוט"],
      gym: [`הסטודיו של ${name}`],
      yoga: [service ? `שיעור ${service}` : "יוגה בוטיק"],
      mat: ["מזרן על עץ"],
      coach: ["מאמן קרוב"],
      weights: ["משקולות לסטודיו קטן"],
      studio: [place ? `סטודיו ב${place}` : `סטודיו ${name}`],
      stretch: ["מתיחה לפני השיעור"],
      group: ["קבוצה קטנה"],
      run: ["צעד בחוץ"],
      work: [`משרד ${name} — מחוץ לנישות`],
      people: [`האנשים של ${name}`],
      screen: ["מסך עבודה"],
      office: ["משרד יום"],
      shop: ["חלל כללי"],
    },
    en: {
      reception: [`${name} — quiet front desk from the site`],
      chair: [service ? `${name}: ${service}` : `${name} treatment chair`],
      tools: ["Details taken from the page — no invented price"],
      hallway: [place ? `Clinic corridor in ${place}` : "Clinic corridor"],
      care: ["Care as written on the site"],
      team: [`Team frame for ${name}`],
      consult: ["First consult — no fake ROAS"],
      calm: [place ? `Calm room, ${place}` : "Calm treatment light"],
      light: [`Soft light for ${name}`],
      desk: [service ? `${service} lesson with ${name}` : `${name} study desk`],
      books: ["Books on the table"],
      classroom: [place ? `A class near ${place}` : "Small classroom"],
      notes: ["Practice notebook"],
      board: [`${name} board`],
      pair: ["Two-person session"],
      write: ["Writing the solution"],
      lecture: ["Explaining at the board"],
      plan: ["Weekly plan from the site"],
      room: [place ? `${name} in ${place}` : `${name} dining room`],
      coffee: ["Morning cup — café identity"],
      plated: [service ? `A ${service} plate` : "A plated dish"],
      table: ["Table for two"],
      street: [place ? `Storefront in ${place}` : "Storefront"],
      dish: ["Dish for the ad frame"],
      cafe: [`Coffee corner at ${name}`],
      pastry: ["Pastry case"],
      evening: ["Evening light"],
      site: [place ? `Job site in ${place}` : `${name} job site`],
      kitchen: [service ? `${service} work` : "Kitchen after a remodel"],
      build: ["Real work — no ROAS claims"],
      paint: ["Walls being painted"],
      interior: ["Interior after work"],
      crew: ["Crew on site"],
      home: ["A home mid-refresh"],
      space: ["Empty room before furniture"],
      gym: [`${name} studio floor`],
      yoga: [service ? `${service} class` : "Boutique yoga"],
      mat: ["Mat on wood"],
      coach: ["A nearby coach"],
      weights: ["Light iron for a boutique room"],
      studio: [place ? `Studio in ${place}` : `${name} studio`],
      stretch: ["Stretch before class"],
      group: ["Small group"],
      run: ["A step outside"],
      work: [`${name} workspace — outside our niches`],
      people: [`People around ${name}`],
      screen: ["A work screen"],
      office: ["Daytime office"],
      shop: ["Generic shop light"],
    },
  };

  const options = packs[lang][stock.theme] || packs[lang].work || [`${name} — ${stock.theme}`];
  return options[index % options.length];
}

export function imagesForFacts(facts: BusinessFacts, lang: Lang): NicheImage[] {
  const pack = STOCK[facts.niche] || STOCK.out_of_niche;
  const used = new Set<string>();
  return pack.map((stock, index) => {
    let caption = captionFor(stock, facts, lang, index);
    if (used.has(caption)) caption = `${caption} · ${index + 1}`;
    used.add(caption);
    return {
      id: stock.id,
      src: stock.src,
      alt: caption,
      caption,
    };
  });
}
