import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const beautyAesthetic: NicheDefinition = {
  id: "beauty_aesthetic",
  labels: { ar: "تجميل وصالونات", he: "אסתטיקה ומספרות", en: "Beauty & aesthetic" },
  keywords: [
    "تجميل",
    "صالون",
    "كوافير",
    "بشرة",
    "جلدية تجميل",
    "بوتوكس",
    "فيلر",
    "ليزر",
    "مكياج",
    "أظافر",
    "salon",
    "aesthetic",
    "beauty",
    "botox",
    "filler",
    "laser",
    "hair salon",
    "מספרה",
    "אסתטיקה",
    "קוסמטי",
    "לייזר",
    "בוטוקס",
  ],
  strongKeywords: ["صالون تجميل", "عيادة تجميل", "מספרה", "aesthetic clinic", "بوتوكس"],
  vetoKeywords: ["أسنان", "dental", "محامي", "مقاول", "مطعم", "طب الأطفال"],
  scanPriority: ["name", "phone", "whatsapp", "services", "place", "hours"],
  ctaStyle: "whatsapp",
  serviceCatalog: [
    "بوتوكس",
    "فيلر",
    "ليزر",
    "صبغة",
    "قص",
    "عناية بشرة",
    "botox",
    "filler",
    "laser",
    "תספורת",
    "לייזר",
  ],
  stockQueries: [
    "hair salon chair warm",
    "skincare facial aesthetic",
    "beauty studio interior",
    "laser aesthetic room clean",
    "makeup vanity lights",
  ],
  motifs: [
    motif("b1", "chair", "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=900&q=80", ["salon chair"], "كرسي الصالون — {name}", "כיסא המספרה — {name}", "salon chair — {name}"),
    motif("b2", "mirror", "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=900&q=80", ["mirror"], "مرآة {name}", "מראה {name}", "{name} mirror"),
    motif("b3", "skin", "https://images.unsplash.com/photo-1570172619604-71d8825d72cb?w=900&q=80", ["facial"], "بشرة عند {name}", "עור אצל {name}", "skin at {name}"),
    motif("b4", "tools", "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=900&q=80", ["beauty tools"], "عدة {name}", "כלים של {name}", "{name} tools"),
    motif("b5", "light", "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=900&q=80", ["vanity"], "ضوء {name}", "אור {name}", "{name} light"),
    motif("b6", "studio", "https://images.unsplash.com/photo-1519415387720-5d1c2d1c0b1a?w=900&q=80", ["studio"], "ستوديو {name}{place}", "סטודיו {name}", "{name} studio"),
    motif("b7", "hands", "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=900&q=80", ["nails"], "عناية عند {name}", "טיפוח אצל {name}", "care at {name}"),
    motif("b8", "team", "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=900&q=80", ["stylist"], "ستايلست {name}", "סטייליסט {name}", "{name} stylist"),
    motif("b9", "calm", "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=900&q=80", ["spa calm"], "هدوء {name}", "שקט {name}", "calm {name}"),
  ],
  copy: [
    T("headline", "name-only", "هاي صالون / تجميل {name}", "זה הסלון/אסתטיקה {name}", "This is beauty studio {name}", "شوف الشغل", "ראו עבודה", "See the work"),
    T("headline", "name-place", "تجميل في {place}: {name}", "אסתטיקה ב{place}: {name}", "Beauty in {place}: {name}", "شوف وين", "איפה", "See where", "place"),
    T("headline", "service-name", "{service} عند {name}", "{service} אצל {name}", "{service} at {name}", "شوف الخدمة", "ראו שירות", "See the service", "service"),
    T("headline", "near-you", "قريب عليك في {place} — {name}", "קרוב ב{place} — {name}", "Near you in {place} — {name}", "اسأل موعد", "שאלו תור", "Ask a slot", "place"),
    T("headline", "today", "بدك تخلّصها اليوم عند {name}؟", "לסגור את זה היום אצל {name}?", "Want it done today at {name}?", "يلا احجز", "יאללה", "Go"),
    T("headline", "first", "أول زيارة تجميل لـ {name} — على مهلك", "ביקור ראשון אצל {name}", "First beauty visit at {name}", "اقرأ", "קראו", "Read"),
    T("headline", "hours", "{name} فاتح {hours}", "{name} פתוח {hours}", "{name} is open {hours}", "لحّق", "תספיקו", "Catch", "hours"),
    T("headline", "question", "وينك عن صالون؟ {name} هون", "מחפשים מספרה? {name} כאן", "Need a salon? {name} is here", "كمّل", "המשיכו", "Continue"),
    T("headline", "hello", "أهلا في {name}", "ברוכים הבאים ל{name}", "Welcome to {name}", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "همّك {service}؟ مكتوب عند {name}", "צריכים {service}? זה אצל {name}", "Need {service}? {name} lists it", "تأكّد", "וודאו", "Confirm", "service"),
    T("headline", "ready", "{name} الكرسي فاضي", "{name} הכיסא פנוי", "{name} has a chair open", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لكرسي {name}", "צעד אחד לכיסא {name}", "One step to {name}’s chair", "خذ الخطوة", "צעד", "Step"),
    T("hook", "pain", "زهقت صالون وميعاد؟ {name} قدامك.", "נמאס ממספרה ותור? {name} כאן.", "Tired of salon-hunting? {name} is here.", "اسأل", "שאלו", "Ask"),
    T("hook", "neighbor", "جارتك في {place} بتمرّ على {name}.", "השכנה ב{place} כבר אצל {name}.", "Your neighbor in {place} already goes to {name}.", "اسألي", "שאלו", "Ask around", "place"),
    T("hook", "who", "بتدور {service}؟ صفحة {name} إلك.", "מחפשים {service}? העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
    T("hook", "week", "هالأسبوع فيك تحجزي عند {name}.", "השבוע אפשר לקבוע אצל {name}.", "This week you can book {name}.", "خطّط", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: {name}.", "עצרו: {name}.", "Stop: {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب الصالون {phone}", "וואטסאפ לסלון {phone}", "WhatsApp the studio {phone}", "ابعت", "שלחו", "Message", "phone"),
    T("hook", "call-easy", "اتّصلي {phone} واسألي أقرب كرسي", "התקשרו {phone} לכיסא", "Call {phone} for the next chair", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم صالون: {name}.", "השם סלון: {name}.", "The name is a studio: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للكرسي.", "{name} — מהקישור לכיסא.", "{name} — from the link to the chair.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: احجزي عند {name}.", "בלי טפסים: קבעו אצל {name}.", "No form: book {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "احجز كرسي من صفحة {name}", "קבעו כיסא מעמוד {name}", "Book a chair on {name}’s page", "احجز كرسي", "קבעו כיסא", "Book a chair"),
    T("cta", "call", "اتّصل {phone} واسأل الجدول", "התקשרו {phone} ליומן", "Call {phone} for the book", "اسأل الجدول", "שאלו יומן", "Ask the book", "phone"),
    T("cta", "consult", "اسأل {name} عن {service}", "שאלו את {name} על {service}", "Ask {name} about {service}", "اسأل قبل", "שאלו קודם", "Ask first", "service"),
    T("cta", "map", "الصالون في {place}", "הסלון ב{place}", "The studio is in {place}", "خذ الاتجاه", "ניווט", "Directions", "place"),
    T("cta", "wa", "واتساب التجميل {phone}", "וואטסאפ לאסתטיקה {phone}", "WhatsApp beauty {phone}", "واتساب الصالون", "וואטסאפ סלון", "WhatsApp salon", "phone"),
    T("cta", "ask-service", "أكّد إنهم بعملوا {service}", "אשרו שהם עושים {service}", "Confirm they do {service}", "أكّד", "אשרו", "Confirm", "service"),
    T("cta", "visit-site", "زور صفحة {name}", "בקרו בעמוד {name}", "Visit {name}’s page", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ موعد {name}", "שמרו תור אצל {name}", "Save a slot at {name}", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتبي إنك بدك كرسي عند {name}", "כתבו שאתם צריכים כיסא אצל {name}", "Write that you need a chair at {name}", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح {name} هسا", "פתחו את {name} עכשיו", "Open {name} now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "دوام الصالون: {hours}.", "שעות הסלון: {hours}.", "Studio hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الكرسي من رابط {name}.", "בלי סיבוב — הכיסא מקישור {name}.", "No maze — the chair is on {name}’s link.", "كمّل", "המשיכו", "Follow"),
    T("headline", "family", "خد أختك أو أمك على {name}", "קחו אחות או אמא ל{name}", "Bring your sister or mum to {name}", "احكي بالبيت", "דברו בבית", "Talk at home"),
    T("cta", "photos", "ابعِتي صورة الشعر أو البشرة لـ {name}", "שלחו תמונה ל{name}", "Send a hair/skin photo to {name}", "ابعت صورة", "שלחו תמונה", "Send a photo"),
  ],
};
