import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const contractors: NicheDefinition = {
  id: "contractors",
  labels: { ar: "مقاولون وتجديد", he: "שיפוצים", en: "Contractors & renovation" },
  keywords: [
    "مقاول",
    "مقاولات",
    "ترميم",
    "تجديد",
    "تشطيب",
    "ديكور",
    "دهان",
    "بلاط",
    "جبس",
    "renovation",
    "contractor",
    "remodel",
    "tiling",
    "kitchen remodel",
    "שיפוץ",
    "קבלן",
    "שיפוצים",
    "צביעה",
  ],
  strongKeywords: ["مقاول ترميم", "שיפוץ דירה", "kitchen remodel", "تشطيب شقة"],
  vetoKeywords: ["سباك طوارئ", "كهرباء 24", "emergency plumber", "عيادة", "مطعم", "محامي"],
  scanPriority: ["name", "phone", "whatsapp", "place", "services", "hours"],
  ctaStyle: "whatsapp",
  serviceCatalog: [
    "دهان",
    "بلاط",
    "مطابخ",
    "حمامات",
    "جبس",
    "painting",
    "tiling",
    "kitchens",
    "צביעה",
    "שיפוץ מטבח",
  ],
  stockQueries: [
    "home renovation dust sunlight",
    "kitchen remodel in progress",
    "painter roller wall",
    "contractor tools belt",
    "bathroom tiling close",
  ],
  motifs: [
    motif("n1", "site", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&q=80", ["site"], "ورشة {name}{place}", "אתר {name}", "{name} site"),
    motif("n2", "kitchen", "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&q=80", ["kitchen"], "مطبخ مع {name}", "מטבח עם {name}", "kitchen with {name}"),
    motif("n3", "build", "https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=900&q=80", ["build"], "شغل {name} عالعظم", "שלד עם {name}", "structure with {name}"),
    motif("n4", "paint", "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?w=900&q=80", ["paint"], "دهان {name}", "צביעה {name}", "{name} paint"),
    motif("n5", "tools", "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900&q=80", ["tools"], "عدة {name}", "כלים של {name}", "{name} tools"),
    motif("n6", "interior", "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=900&q=80", ["interior"], "داخل شغل {name}", "פנים {name}", "{name} interior"),
    motif("n7", "crew", "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&q=80", ["crew"], "طاقم {name}", "צוות {name}", "{name} crew"),
    motif("n8", "home", "https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=900&q=80", ["home"], "بيت مع {name}", "בית עם {name}", "a home with {name}"),
    motif("n9", "space", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80", ["empty space"], "مساحة قبل فرش {name}", "חלל לפני {name}", "space before {name}"),
  ],
  copy: [
    T("headline", "name-only", "هاي مقاول {name}", "זה הקבלן {name}", "This is contractor {name}", "شوف الشغل", "ראו עבודה", "See the work"),
    T("headline", "name-place", "بيت في {place} عم يتجدّد مع {name}", "בית ב{place} מתחדש עם {name}", "A home in {place} refreshing with {name}", "شوف المنطقة", "ראו אזור", "See the area", "place"),
    T("headline", "home", "تجديد بيت مع {name}", "שיפוץ בית עם {name}", "Home renovation with {name}", "شوف قبل/بعد", "ראו לפני/אחרי", "See before/after"),
    T("headline", "service-name", "{service} مع المقاول {name}", "{service} עם הקבלן {name}", "{service} with contractor {name}", "شوف الخدمة", "ראו שירות", "See the service", "service"),
    T("headline", "near-you", "قريب عليك في {place}: {name}", "קרוב ב{place}: {name}", "Near you in {place}: {name}", "اسأل", "שאלו", "Ask", "place"),
    T("headline", "today", "بدك تكشف البيت هالأسبوع مع {name}؟", "ביקור בית השבוע עם {name}?", "House visit this week with {name}?", "يلا رتب", "יאללה", "Go"),
    T("headline", "hours", "{name} بيرد {hours}", "{name} זמין {hours}", "{name} answers {hours}", "لحّق", "תספיקו", "Catch", "hours"),
    T("headline", "question", "وينك عن مقاول؟ {name} هون", "מחפשים קבלן? {name} כאן", "Need a contractor? {name} is here", "كمّل", "המשיכו", "Continue"),
    T("headline", "hello", "مقاولات {name}", "קבלנות {name}", "{name} contracting", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا الحيطان بدها {service} — اسأل {name}", "אם הקיר צריך {service} — שאלו את {name}", "If the wall needs {service} — ask {name}", "اسأل", "שאלו", "Ask", "service"),
    T("headline", "ready", "{name} جاهز يشوف الزاوية", "{name} מוכן לראות את הפינה", "{name} is ready to see the corner", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لكشف {name}", "צעד אחד לביקור של {name}", "One step to {name}’s visit", "خذ الخطوة", "צעד", "Step"),
    T("hook", "wall", "الحيط بده {service}؟ اسأل {name}.", "הקיר צריך {service}? שאלו את {name}.", "Need {service} on the wall? Ask {name}.", "اسأل المقاول", "שאלו קבלן", "Ask the contractor", "service"),
    T("hook", "pain", "زهقت مقاول يوعد وما بيجي؟ اسأل صفحة {name}.", "נמאס מקבלן שלא מגיע? העמוד של {name}.", "Tired of no-shows? {name}’s page is here.", "اسأل", "שאלו", "Ask"),
    T("hook", "neighbor", "جارك في {place} جدّد مع {name}.", "השכן ב{place} שיפץ עם {name}.", "A neighbor in {place} renovated with {name}.", "اسأل عنهم", "שאלו", "Ask around", "place"),
    T("hook", "week", "هالأسبوع فيك تطلب كشف من {name}.", "השבוע אפשר ביקור מ{name}.", "This week you can request a visit from {name}.", "خطّط", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: مقاول {name}.", "עצרו: קבלן {name}.", "Stop: contractor {name}.", "كمّל", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب المقاول {phone}", "וואטסאפ לקבלן {phone}", "WhatsApp the contractor {phone}", "ابعت", "שלחו", "Message", "phone"),
    T("hook", "call-easy", "اتّصل {phone} ووصف الشغل", "התקשרו {phone} ותארו עבודה", "Call {phone} and describe the job", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم مقاول: {name}.", "השם קבלן: {name}.", "The name is a contractor: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للكشف.", "{name} — מהקישור לביקור.", "{name} — from the link to a visit.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: اطلب كشف من {name}.", "בלי טפסים: בקשו ביקור מ{name}.", "No form: request a visit from {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "اطلب كشف بيت من {name}", "בקשו ביקור בית מ{name}", "Request a house visit from {name}", "اطلب كشف", "בקשו ביקור", "Request a visit"),
    T("cta", "call", "اتّصل {phone} ووصف الشغل", "התקשרו {phone} ותארו את העבודה", "Call {phone} and describe the job", "وصف الشغل", "תארו עבודה", "Describe the job", "phone"),
    T("cta", "photos", "ابعِت صور الزاوية لـ {name}", "שלחו תמונות לפינה ל{name}", "Send room photos to {name}", "ابعت صور", "שלחו תמונות", "Send photos"),
    T("cta", "map", "المقاول في {place}: {name}", "הקבלן ב{place}: {name}", "The contractor in {place}: {name}", "حدد المنطقة", "סמנו אזור", "Mark the area", "place"),
    T("cta", "wa", "واتساب المقاول {phone}", "וואטסאפ לקבלן {phone}", "WhatsApp contractor {phone}", "واتساب المقاول", "וואטסאפ קבלן", "WhatsApp contractor", "phone"),
    T("cta", "scope", "أكّد إذا بعملوا {service}", "אשרו אם הם עושים {service}", "Confirm they do {service}", "أكّد الخدمة", "אשרו שירות", "Confirm the service", "service"),
    T("cta", "visit-site", "زور شغل {name}", "בקרו בעבודות {name}", "Visit {name}’s work page", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ مقاول {name}", "שמרו את הקבלן {name}", "Save contractor {name}", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب مساحة الشغل لـ {name}", "כתבו היקף ל{name}", "Write the scope to {name}", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح صفحة {name} هسا", "פתחו את {name} עכשיו", "Open {name} now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "أوقات الرد: {hours}.", "שעות מענה: {hours}.", "Reply hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الكشف من رابط {name}.", "בלי סיבוב — הביקור מקישור {name}.", "No maze — the visit is on {name}’s link.", "كمّل", "המשיכו", "Follow"),
    T("headline", "family", "اتفقوا بالبيت واستشيروا {name}", "דברו בבית והתייעצו עם {name}", "Talk at home, then ask {name}", "احكي بالبيت", "דברו בבית", "Talk at home"),
    T("hook", "who", "بتدور {service}؟ صفحة {name} إلك.", "מחפשים {service}? העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
  ],
};
