import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const dental: NicheDefinition = {
  id: "dental",
  labels: { ar: "عيادات أسنان", he: "מרפאות שיניים", en: "Dental" },
  keywords: [
    "أسنان",
    "اسنان",
    "سنّ",
    "ضرس",
    "تقويم",
    "تبييض",
    "زراعة أسنان",
    "dental",
    "dentist",
    "orthodont",
    "whitening",
    "implants",
    "שיניים",
    "רופא שיניים",
    "הלבנה",
    "יישור",
    "טיפול שיניים",
  ],
  strongKeywords: ["عيادة أسنان", "dental clinic", "מרפאת שיניים", "orthodont", "تقويم أسنان"],
  vetoKeywords: ["أطفال فقط", "pediatric only", "مقاول", "مطعم", "محامي"],
  scanPriority: ["name", "phone", "services", "place", "hours", "whatsapp"],
  ctaStyle: "call",
  forbiddenHooks: ["عيادة هادية", "طفلك بخير", "قلبك مرتاح", "موجوع؟"],
  serviceCatalog: [
    "تقويم",
    "تبييض",
    "زراعة",
    "تنظيف",
    "حشوة",
    "orthodontics",
    "whitening",
    "implants",
    "הלבנה",
    "יישור שיניים",
  ],
  stockQueries: [
    "dental chair clinic bright",
    "dentist tools close up no text",
    "teeth whitening studio",
    "dental reception calm",
    "orthodontics smile consult",
  ],
  motifs: [
    motif("d1", "chair", "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=900&q=80", ["dental chair"], "كرسي الأسنان — {name}", "כיסא שיניים — {name}", "dental chair — {name}"),
    motif("d2", "tools", "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&q=80", ["dental tools"], "عدة الأسنان عند {name}", "כלי שיניים אצל {name}", "dental tools at {name}"),
    motif("d3", "reception", "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=900&q=80", ["dental reception"], "مدخل عيادة الأسنان {name}", "כניסת מרפאת השיניים {name}", "{name} dental entrance"),
    motif("d4", "smile", "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=900&q=80", ["smile"], "ابتسامة شغل {name}", "חיוך של {name}", "{name} smile work"),
    motif("d5", "consult", "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=900&q=80", ["dentist consult"], "استشارة أسنان — {name}", "ייעוץ שיניים — {name}", "dental consult — {name}"),
    motif("d6", "clean", "https://images.unsplash.com/photo-1598256989806-78ae8033d121?w=900&q=80", ["cleaning"], "تنظيف عند {name}", "ניקוי אצל {name}", "cleaning at {name}"),
    motif("d7", "light", "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=900&q=80", ["operatory"], "غرفة العلاج — {name}", "חדר טיפול — {name}", "{name} operatory"),
    motif("d8", "team", "https://images.unsplash.com/photo-1629909615184-74f495363b67?w=900&q=80", ["dental team"], "طاقم الأسنان {name}", "צוות השיניים {name}", "{name} dental team"),
    motif("d9", "street", "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=900&q=80", ["clinic front"], "واجهة {name}{place}", "חזית {name}", "{name} front"),
  ],
  copy: [
    T("headline", "name-only", "هاي عيادة الأسنان {name}", "זו מרפאת השיניים {name}", "This is the dental clinic {name}", "شوف العيادة", "ראו מרפאה", "See the clinic"),
    T("headline", "name-place", "أسنان في {place}: {name}", "שיניים ב{place}: {name}", "Dental in {place}: {name}", "شوف وين", "בדקו איפה", "See where", "place"),
    T("headline", "service-name", "{service} أسنان عند {name}", "{service} שיניים אצל {name}", "Dental {service} at {name}", "شوف الخدمة", "ראו שירות", "See the service", "service"),
    T("headline", "near-you", "قريب عليك سنّك يوجعك؟ {name} في {place}", "כואבות שיניים? {name} ב{place}", "Tooth trouble nearby? {name} in {place}", "اسأل الموعد", "שאלו תור", "Ask a slot", "place"),
    T("headline", "today", "بدك تخلّص السن اليوم مع {name}؟", "לסגור את השן היום עם {name}?", "Want the tooth done today with {name}?", "يلا احجز", "יאללה קבעו", "Book now"),
    T("headline", "first", "أول جلسة أسنان عند {name} — على مهلك", "טיפול שיניים ראשון אצל {name}", "First dental visit at {name} — unhurried", "اقرأ الأسلوب", "קראו סגנון", "Read the style"),
    T("headline", "hours", "عيادة الأسنان {name} فاتحة {hours}", "מרפאת השיניים {name} פתוחה {hours}", "Dental clinic {name} open {hours}", "لحّق الدوام", "תספיקו", "Catch hours", "hours"),
    T("headline", "question", "وينك عن تقويم وتبييض؟ {name} هون", "איפה הייתם מיישור והלבנה? {name} כאן", "Looking for braces or whitening? {name} is here", "كمّل قراءة", "המשיכו", "Keep reading"),
    T("headline", "hello", "عيادة الأسنان {name} بتسلّم عليك", "מרפאת השיניים {name} מברכת", "Dental clinic {name} says hello", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "همّك {service}؟ عيادة {name} مكتوب عندها", "צריכים {service}? זה כתוב אצל {name}", "Need {service}? {name} lists it", "تأكّد من الصفحة", "וודאו בעמוד", "Check the page", "service"),
    T("headline", "ready", "{name} جاهز لسنّك — مش لجملة فاضي", "{name} מוכן לשן — לא לסלוגן", "{name} is ready for the tooth — not a slogan", "احكي هسا", "דברו", "Talk now"),
    T("headline", "one-step", "خطوة وحدة لكرسي {name}", "צעד אחד לכיסא של {name}", "One step to {name}’s chair", "خذ الخطوة", "צעד", "Take a step"),
    T("hook", "pain", "الضرس ما بستنى. صفحة {name} قدامك.", "השן לא מחכה. העמוד של {name} כאן.", "The tooth will not wait. {name}’s page is here.", "اسأل الموعد", "שאלו תור", "Ask a time"),
    T("hook", "neighbor", "جارك في {place} بصلّح سنّه عند {name}.", "השכן ב{place} מטפל בשיניים אצל {name}.", "Your neighbor in {place} sees {name} for teeth.", "اسأل عنهم", "שאלו עליהם", "Ask around", "place"),
    T("hook", "who", "إذا بتدور {service} للأسنان — {name} إلك.", "אם מחפשים {service} לשיניים — {name} בשבילכם.", "Looking for dental {service}? {name} is for you.", "اختار الخدمة", "בחרו", "Pick it", "service"),
    T("hook", "week", "هالأسبوع فيك تحجز كرسي عند {name}.", "השבוע אפשר לקבוע כיסא אצל {name}.", "This week you can book a chair at {name}.", "خطّط الجلسة", "תכננו", "Plan it"),
    T("hook", "scroll", "وقّف السكرول: عيادة أسنان {name}.", "עצרו: מרפאת שיניים {name}.", "Stop: dental clinic {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب عيادة الأسنان {phone}", "וואטסאפ למרפאת השיניים {phone}", "WhatsApp the dentist {phone}", "ابعت هسا", "שלחו", "Message now", "phone"),
    T("hook", "call-easy", "اتّصل {phone} واسأل أقرب كرسي", "התקשרו {phone} לכיסא פנוי", "Call {phone} for the next chair", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم مكتوب: عيادة الأسنان {name}.", "השם: מרפאת השיניים {name}.", "The name is the dental clinic {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "سنّك و{name} — من الرابط، مش من شعار.", "השן ו{name} — מהקישור, לא מסלוגן.", "Your tooth and {name} — from the link, not a slogan.", "افتح الرابط", "פתחו", "Open the link"),
    T("hook", "direct", "بلا لف: روح على عيادة الأسنان {name}.", "בלי סיבוב: למרפאת השיניים {name}.", "No detour: go to dental clinic {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "احجز كرسي أسنان من صفحة {name}", "קבעו כיסא שיניים מעמוד {name}", "Book a dental chair on {name}’s page", "احجز كرسي", "קבעו כיסא", "Book a chair"),
    T("cta", "call", "اتّصل {phone} لموعد أسنان", "התקשרו {phone} לתור שיניים", "Call {phone} for a dental slot", "اتّصل للسن", "התקשרו לשן", "Call for a tooth", "phone"),
    T("cta", "consult", "اسأل {name} عن التقويم أو التبييض", "שאלו את {name} על יישור או הלבנה", "Ask {name} about braces or whitening", "اسأل قبل", "שאלו קודם", "Ask first"),
    T("cta", "map", "اتجه على عيادة الأسنان في {place}", "נווטו למרפאת השיניים ב{place}", "Head to the dental clinic in {place}", "خذ الاتجاه", "ניווט", "Directions", "place"),
    T("cta", "wa", "واتساب سنّك على {phone}", "וואטסאפ לשן ב{phone}", "WhatsApp the tooth line {phone}", "واتساب الأسنان", "וואטסאפ שיניים", "WhatsApp dental", "phone"),
    T("cta", "ask-service", "أكّد إنهم بعملوا {service}", "אשרו שהם עושים {service}", "Confirm they do {service}", "أكّد", "אשרו", "Confirm", "service"),
    T("cta", "visit-site", "زور صفحة عيادة الأسنان {name}", "בקרו בעמוד מרפאת השיניים {name}", "Visit {name}’s dental page", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ موعد الأسنان — صفحة {name}", "שמרו את עמוד השיניים של {name}", "Save {name}’s dental page", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب إنك بدك موعد أسنان عند {name}", "כתבו שאתם צריכים תור שיניים אצל {name}", "Write that you need a dental slot at {name}", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح عيادة الأسنان {name} هسا", "פתחו את מרפאת השיניים {name} עכשיו", "Open dental clinic {name} now", "افتح", "פתחו", "Open"),
    T("headline", "family", "خد أهلك لتبييض أو تنظيف عند {name}", "קחו את המשפחה להלבנה אצל {name}", "Bring the family for a clean or whitening at {name}", "احكي بالبيت", "דברו בבית", "Talk at home"),
    T("hook", "hours-hook", "دوام عيادة الأسنان: {hours}.", "שעות מרפאת השיניים: {hours}.", "Dental hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("cta", "photos", "ابعِت صورة السن لـ {name} من الصفحة", "שלחו תמונת שן ל{name}", "Send a tooth photo to {name} from the page", "ابعت صورة", "שלחו תמונה", "Send a photo"),
    T("hook", "no-form", "ما في لف — موعد الأسنان من رابط {name}.", "בלי טפסים — תור השיניים מקישור {name}.", "No form maze — dental slot from {name}’s link.", "كمّل الرابط", "המשיכו", "Follow"),
  ],
};
