import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const fitness: NicheDefinition = {
  id: "fitness",
  labels: { ar: "صالات ومدربون", he: "כושר", en: "Gyms & trainers" },
  keywords: [
    "نادي رياضي",
    "لياقة",
    "جيم",
    "يوغا",
    "بيلاتس",
    "كروسفت",
    "مدرب",
    "gym",
    "fitness",
    "yoga",
    "pilates",
    "boutique fitness",
    "personal train",
    "חדר כושר",
    "יוגה",
    "פילאטיס",
    "אימון אישי",
    "כושר",
  ],
  strongKeywords: ["حصة يوغا", "אימון אישי", "personal training", "ستوديو لياقة"],
  vetoKeywords: ["عيادة أسنان", "مطعم", "محامي", "مقاول", "dental"],
  scanPriority: ["name", "place", "phone", "hours", "services", "whatsapp"],
  ctaStyle: "whatsapp",
  serviceCatalog: [
    "يوغا",
    "بيلاتس",
    "كارديو",
    "شخصي",
    "yoga",
    "pilates",
    "personal training",
    "יוגה",
    "פילאטיס",
    "אימון אישי",
  ],
  stockQueries: [
    "boutique gym interior",
    "yoga studio mats",
    "personal trainer coaching",
    "dumbbell rack warm light",
    "small group fitness",
  ],
  motifs: [
    motif("f1", "gym", "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=900&q=80", ["gym"], "بساط {name}", "מזרן {name}", "{name} floor"),
    motif("f2", "yoga", "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=900&q=80", ["yoga"], "يوغا {name}", "יוגה {name}", "{name} yoga"),
    motif("f3", "mat", "https://images.unsplash.com/photo-1518611012118-696072451274?w=900&q=80", ["mat"], "مات {name}", "מזרן {name}", "{name} mat"),
    motif("f4", "coach", "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=900&q=80", ["coach"], "مدرب {name}", "מאמן {name}", "{name} coach"),
    motif("f5", "weights", "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=900&q=80", ["weights"], "حديد {name}", "משקולות {name}", "{name} weights"),
    motif("f6", "studio", "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=900&q=80", ["studio"], "ستوديو {name}{place}", "סטודיו {name}", "{name} studio"),
    motif("f7", "stretch", "https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=900&q=80", ["stretch"], "تمسيد {name}", "מתיחה {name}", "{name} stretch"),
    motif("f8", "group", "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=900&q=80", ["group"], "مجموعة {name}", "קבוצה {name}", "{name} group"),
    motif("f9", "run", "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=900&q=80", ["run"], "خطوة برّا مع {name}", "צעד בחוץ עם {name}", "outside with {name}"),
  ],
  copy: [
    T("headline", "name-only", "هاي ستوديو {name}", "זה הסטודיו {name}", "This is studio {name}", "شوف الحصص", "ראו שיעורים", "See classes"),
    T("headline", "name-place", "ستوديو صغير في {place}: {name}", "סטודיו קטן ב{place}: {name}", "A small studio in {place}: {name}", "شوف وين", "איפה", "See where", "place"),
    T("headline", "boutique", "جيم بوتيك: {name}", "חדר כושר בוטיק: {name}", "Boutique gym: {name}", "شوف المكان", "ראו מקום", "See the room"),
    T("headline", "service-name", "{service} عند {name}", "{service} אצל {name}", "{service} at {name}", "شوف الحصة", "ראו שיעור", "See the class", "service"),
    T("headline", "near-you", "قريب عليك في {place}: {name}", "קרוב ב{place}: {name}", "Near you in {place}: {name}", "اسأل", "שאלו", "Ask", "place"),
    T("headline", "today", "بدك تتحرك اليوم عند {name}؟", "לזוז היום אצל {name}?", "Move today at {name}?", "يلا احجز", "יאללה", "Go"),
    T("headline", "hours", "{name} فاتح {hours}", "{name} פתוח {hours}", "{name} is open {hours}", "لحّق", "תספיקו", "Catch", "hours"),
    T("headline", "question", "وينك عن حصة؟ {name} هون", "מחפשים שיעור? {name} כאן", "Need a class? {name} is here", "كمّل", "המשיכו", "Continue"),
    T("headline", "hello", "أهلا في {name}", "ברוכים הבאים ל{name}", "Welcome to {name}", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا {service} بناسبك — {name} مكتوب", "אם {service} מתאים — זה אצל {name}", "If {service} fits — {name} lists it", "تأكّد", "וודאו", "Confirm", "service"),
    T("headline", "ready", "{name} المات جاهز", "{name} המזרן מוכן", "{name} has a mat ready", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لحصة {name}", "צעד אחד לשיעור {name}", "One step to a class at {name}", "خذ الخطوة", "צעד", "Step"),
    T("hook", "breath", "بدك تتنفس شوي؟ {service} عند {name}.", "צריכים לנשום? {service} אצל {name}.", "Need a breath? {service} at {name}.", "ادخل الجدول", "כנסו למערכת", "Open the schedule", "service"),
    T("hook", "pain", "زهقت جيم كبير؟ {name} قدامك.", "נמאס מחדר גדול? {name} כאן.", "Tired of a huge gym? {name} is here.", "اسأل", "שאלו", "Ask"),
    T("hook", "neighbor", "جارك في {place} بتمرّن عند {name}.", "השכן ב{place} מתאמן אצל {name}.", "A neighbor in {place} trains at {name}.", "اسأل عنهم", "שאלו", "Ask around", "place"),
    T("hook", "week", "هالأسبوع فيك تجرّب حصة عند {name}.", "השבוע אפשר לנסות שיעור אצל {name}.", "This week you can try a class at {name}.", "خطّط", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: ستوديو {name}.", "עצרו: סטודיו {name}.", "Stop: studio {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب الاستوديو {phone}", "וואטסאפ לסטודיו {phone}", "WhatsApp the studio {phone}", "ابعت", "שלחו", "Message", "phone"),
    T("hook", "call-easy", "اتّصل {phone} واسأل الجدول", "התקשרו {phone} למערכת", "Call {phone} for the timetable", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم ستوديو: {name}.", "השם סטודיו: {name}.", "The name is a studio: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للمات.", "{name} — מהקישור למזרן.", "{name} — from the link to the mat.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: احجز حصة عند {name}.", "בלי טפסים: קבעו שיעור אצל {name}.", "No form: book a class at {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "احجز حصة عند {name}", "קבעו שיעור אצל {name}", "Book a class at {name}", "احجز حصة", "קבעו שיעור", "Book a class"),
    T("cta", "call", "اتّصل {phone} واسأل الجدول", "התקשרו {phone} למערכת", "Call {phone} for the timetable", "اسأل الجدول", "שאלו מערכת", "Ask the timetable", "phone"),
    T("cta", "trial", "جرّب حصة أولى مع {name}", "נסו שיעור ראשון עם {name}", "Try a first class with {name}", "جرّب حصة", "נסו שיעור", "Try a class"),
    T("cta", "map", "الاستوديو في {place}", "הסטודיו ב{place}", "The studio is in {place}", "خذ الاتجاه", "ניווט", "Directions", "place"),
    T("cta", "wa", "واتساب الاستوديو {phone}", "וואטסאפ לסטודיו {phone}", "WhatsApp the studio {phone}", "واتساب الحصة", "וואטסאפ לשיעור", "WhatsApp the class", "phone"),
    T("cta", "mat", "احجز مات لـ {service}", "שמרו מזרן ל{service}", "Hold a mat for {service}", "احجز مات", "שמרו מזרן", "Hold a mat", "service"),
    T("cta", "visit-site", "زور جدول {name}", "בקרו במערכת {name}", "Visit {name}’s schedule", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ حصة {name}", "שמרו שיעור אצל {name}", "Save a class at {name}", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب إنك بدك حصة تجريبية", "כתבו שאתם רוצים ניסיון", "Write that you want a trial", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح {name} هسا", "פתחו את {name} עכשיו", "Open {name} now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "دوام الاستوديو: {hours}.", "שעות הסטודיו: {hours}.", "Studio hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الحصة من رابط {name}.", "בלי סיבוב — השיעור מקישור {name}.", "No maze — the class is on {name}’s link.", "كمّל", "המשיכו", "Follow"),
    T("headline", "family", "خد رفيقك على حصة {name}", "קחו חבר לשיעור {name}", "Bring a friend to a class at {name}", "احكي", "דברו", "Talk"),
    T("hook", "who", "بتدور {service}؟ صفحة {name} إلك.", "מחפשים {service}? העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
  ],
};
