import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const homeTrades: NicheDefinition = {
  id: "home_trades",
  labels: { ar: "خدمات بيت طارئة", he: "שירותי בית דחופים", en: "Urgent home trades" },
  keywords: [
    "سباك",
    "سباكة",
    "كهربائي",
    "كهرباء",
    "تكييف",
    "مكيف",
    "تدفئة",
    "غاز",
    "تسريب",
    "طوارئ",
    "24 ساعة",
    "plumber",
    "electrician",
    "hvac",
    "air condition",
    "emergency",
    "leak",
    "אינסטלטור",
    "חשמלאי",
    "מזגנים",
    "חירום",
    "נזילה",
  ],
  strongKeywords: ["سباك طوارئ", "كهربائي 24", "emergency plumber", "נזילה", "تكييف معطل"],
  vetoKeywords: ["تجديد شقة كامل", "kitchen remodel", "عيادة", "مطعم", "محامي", "dental"],
  scanPriority: ["phone", "whatsapp", "name", "place", "services", "hours"],
  ctaStyle: "call",
  serviceCatalog: [
    "سباكة",
    "كهرباء",
    "تكييف",
    "تسريب",
    "plumbing",
    "electrical",
    "HVAC",
    "אינסטלציה",
    "חשמל",
    "מזגן",
  ],
  stockQueries: [
    "plumber under sink",
    "electrician fuse box",
    "hvac technician outdoor unit",
    "pipe wrench close",
    "home repair van",
  ],
  motifs: [
    motif("h1", "pipes", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=900&q=80", ["pipes"], "مواسير — {name}", "צינורות — {name}", "pipes — {name}"),
    motif("h2", "wrench", "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900&q=80", ["wrench"], "مفتاح {name}", "מפתח {name}", "{name} wrench"),
    motif("h3", "electric", "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=900&q=80", ["electric"], "كهرباء مع {name}", "חשמל עם {name}", "electrics with {name}"),
    motif("h4", "hvac", "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=900&q=80", ["hvac"], "مكيف — {name}", "מזגן — {name}", "AC — {name}"),
    motif("h5", "van", "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=900&q=80", ["van"], "سيارة شغل {name}", "רכב עבודה {name}", "{name} van"),
    motif("h6", "sink", "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=900&q=80", ["sink"], "حوض مع {name}", "כיור עם {name}", "a sink with {name}"),
    motif("h7", "crew", "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&q=80", ["tech"], "فني {name}", "טכנאי {name}", "{name} tech"),
    motif("h8", "home", "https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=900&q=80", ["home"], "بيت بستنى {name}", "בית מחכה ל{name}", "a home waiting for {name}"),
    motif("h9", "night", "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=900&q=80", ["after hours"], "بعد الدوام — {name}", "אחרי שעות — {name}", "after hours — {name}"),
  ],
  copy: [
    T("headline", "name-only", "هاي {name} — سباكة / كهربا / تكييف", "זה {name} — אינסטלציה / חשמל / מזגן", "This is {name} — plumb / elec / HVAC", "اتّصل", "התקשרו", "Call"),
    T("headline", "name-place", "طوارئ بيت في {place}: {name}", "חירום בית ב{place}: {name}", "Home emergency in {place}: {name}", "اتّصل هسا", "התקשרו עכשיו", "Call now", "place"),
    T("headline", "service-name", "{service} طارئة مع {name}", "{service} דחוף עם {name}", "Urgent {service} with {name}", "وصف العطل", "תארו תקלה", "Describe the fault", "service"),
    T("headline", "near-you", "قريب عليك في {place} — {name}", "קרוב ב{place} — {name}", "Near you in {place} — {name}", "اسأل الوصول", "שאלו הגעה", "Ask ETA", "place"),
    T("headline", "today", "بدك تخلّص العطل اليوم مع {name}؟", "לסגור את התקלה היום עם {name}?", "Want the fault fixed today with {name}?", "يلا اتّصل", "יאללה התקשרו", "Call"),
    T("headline", "first", "أول كشف عطل مع {name} — على مهلك بالشرح", "אבחון ראשון עם {name}", "First fault visit with {name}", "اقرأ", "קראו", "Read"),
    T("headline", "hours", "{name} بيرد {hours}", "{name} זמין {hours}", "{name} answers {hours}", "لحّق", "תספיקו", "Catch", "hours"),
    T("headline", "question", "في تسريب أو شورت؟ {name} هون", "נזילה או קצר? {name} כאן", "A leak or a short? {name} is here", "كمّل", "המשיכו", "Continue"),
    T("headline", "hello", "فني بيت {name}", "טכנאי בית {name}", "Home tech {name}", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا {service} واقفة — اسأل {name}", "אם {service} תקוע — שאלו את {name}", "If {service} is down — ask {name}", "اسأل", "שאלו", "Ask", "service"),
    T("headline", "ready", "{name} جاهز يطلع", "{name} מוכן לצאת", "{name} is ready to roll", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لاتّصال {name}", "צעד אחד לשיחה עם {name}", "One step to calling {name}", "خذ الخطوة", "צעד", "Step"),
    T("hook", "pain", "الموية نازلة؟ الكهربا قاطعة؟ صفحة {name}.", "מים יורדים? חשמל נפל? העמוד של {name}.", "Water down? Power out? {name}’s page.", "اتّصل", "התקשרו", "Call"),
    T("hook", "urgent", "العطل ما بستنى شعارات. {name} قدامك.", "התקלה לא מחכה לסלוגן. {name} כאן.", "The fault will not wait for a slogan. {name} is here.", "اتّصل هسا", "התקשרו עכשיו", "Call now"),
    T("hook", "neighbor", "جارك في {place} نادى {name}.", "השכן ב{place} קרא ל{name}.", "A neighbor in {place} called {name}.", "اسأل عنهم", "שאלו", "Ask around", "place"),
    T("hook", "week", "هالأسبوع فيك تطلب كشف من {name}.", "השבוע אפשר ביקור מ{name}.", "This week you can request a visit from {name}.", "خطّט", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: فني {name}.", "עצרו: טכנאי {name}.", "Stop: tech {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب الفني {phone}", "וואטסאפ לטכנאי {phone}", "WhatsApp the tech {phone}", "ابعت العطل", "שלחו תקלה", "Send the fault", "phone"),
    T("hook", "call-easy", "اتّصل {phone} ووصف العطل", "התקשרו {phone} ותארו תקלה", "Call {phone} and describe the fault", "اتّصل هسا", "התקשרו עכשיו", "Call now", "phone"),
    T("hook", "clear", "الاسم فني: {name}.", "השם טכנאי: {name}.", "The name is a tech: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للتلفون.", "{name} — מהקישור לטלפון.", "{name} — from the link to the phone.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: اتّصل على {name}.", "בלי טפסים: התקשרו ל{name}.", "No form: call {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "اطلب كشف عطل من صفحة {name}", "בקשו ביקור תקלה מעמוד {name}", "Request a fault visit on {name}’s page", "اطلب كشف", "בקשו ביקור", "Request a visit"),
    T("cta", "call", "اتّصل {phone} هسا — مش 101", "התקשרו {phone} עכשיו — לא 101", "Call {phone} now — not 101", "اتّصل للفني", "התקשרו לטכנאי", "Call the tech", "phone"),
    T("cta", "photos", "ابعِت صورة العطل لـ {name}", "שלחו תמונת תקלה ל{name}", "Send a fault photo to {name}", "ابعت صورة", "שלחו תמונה", "Send a photo"),
    T("cta", "map", "الفني في {place}: {name}", "הטכנאי ב{place}: {name}", "The tech in {place}: {name}", "حدد المنطقة", "סמנו אזור", "Mark the area", "place"),
    T("cta", "wa", "واتساب الطوارئ {phone}", "וואטסאפ דחוף {phone}", "Urgent WhatsApp {phone}", "واتساب الفني", "וואטסאפ טכנאי", "WhatsApp tech", "phone"),
    T("cta", "scope", "أكّد إذا بصلحوا {service}", "אשרו אם הם מתקנים {service}", "Confirm they fix {service}", "أكّد", "אשרו", "Confirm", "service"),
    T("cta", "visit-site", "زور صفحة {name}", "בקרו בעמוד {name}", "Visit {name}’s page", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ رقم {name} لليلة", "שמרו את {name} ללילה", "Save {name} for tonight", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب: تسريب / شورت / مكيف", "כתבו: נזילה / קצר / מזגן", "Write: leak / short / AC", "اكتب العطل", "כתבו תקלה", "Write the fault"),
    T("cta", "open-now", "افتح رقم {name} هسا", "פתחו את {name} עכשיו", "Open {name} now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "أوقات الرد: {hours}.", "שעות מענה: {hours}.", "Reply hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الرقم من رابط {name}.", "בלי סיבוב — המספר מקישור {name}.", "No maze — the number is on {name}’s link.", "كمّל", "המשיכו", "Follow"),
    T("headline", "family", "إذا البيت وقف — اسأل {name} مش 911", "אם הבית נעצר — שאלו את {name} לא 911", "If the house stopped — ask {name}, not 911", "اتّصل للمحل", "התקשרו לעסק", "Call the business"),
    T("hook", "who", "بتدور {service}؟ صفحة {name} إلك.", "מחפשים {service}? העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
  ],
};
