import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const lawyers: NicheDefinition = {
  id: "lawyers",
  labels: { ar: "محامون", he: "עורכי דין", en: "Lawyers" },
  keywords: [
    "محامي",
    "محامون",
    "محاماة",
    "استشارة قانونية",
    "عقد",
    "قضية",
    "lawyer",
    "attorney",
    "law office",
    "legal",
    "עורך דין",
    "עורכי דין",
    "משרד עורכי",
    "ייעוץ משפטי",
  ],
  strongKeywords: ["مكتب محاماة", "עורך דין", "law firm", "استشارة قانونية"],
  vetoKeywords: ["عيادة أسنان", "مطعم", "مقاول", "dental"],
  scanPriority: ["name", "phone", "place", "services", "whatsapp", "hours"],
  ctaStyle: "call",
  serviceCatalog: [
    "استشارة",
    "عقود",
    "أحوال شخصية",
    "عقارات",
    "عمل",
    "consultation",
    "contracts",
    "ייעוץ",
    "חוזים",
    "דיני עבודה",
  ],
  stockQueries: [
    "law office desk books no text",
    "lawyer handshake local office",
    "legal library warm light",
    "courthouse columns exterior",
    "contract signing table",
  ],
  motifs: [
    motif("l1", "desk", "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=900&q=80", ["law desk"], "مكتب {name}", "שולחן {name}", "{name} desk"),
    motif("l2", "books", "https://images.unsplash.com/photo-1505664194779-8beace1d547d?w=900&q=80", ["law books"], "كتب {name}", "ספרי {name}", "{name} books"),
    motif("l3", "handshake", "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=900&q=80", ["handshake"], "اتفاق مع {name}", "הסכם עם {name}", "agreement with {name}"),
    motif("l4", "gavel", "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=900&q=80", ["gavel"], "قضية عند {name}", "תיק אצל {name}", "a case at {name}"),
    motif("l5", "columns", "https://images.unsplash.com/photo-1436450412740-6b988f486c6b?w=900&q=80", ["courthouse"], "واجهة {name}", "חזית {name}", "{name} front"),
    motif("l6", "consult", "https://images.unsplash.com/photo-1528747008803-1c3157c4c6d1?w=900&q=80", ["consult"], "جلسة {name}", "פגישה {name}", "{name} meeting"),
    motif("l7", "street", "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80", ["office street"], "مبنى {name}{place}", "בניין {name}", "{name} building"),
    motif("l8", "paper", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80", ["papers"], "أوراق {name}", "ניירות {name}", "{name} papers"),
    motif("l9", "calm", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80", ["quiet office"], "هدوء مكتب {name}", "שקט במשרד {name}", "quiet {name} office"),
  ],
  copy: [
    T("headline", "name-only", "هاي مكتب {name}", "זה המשרד של {name}", "This is {name}’s office", "ادخل شوف", "כנסו", "Come see"),
    T("headline", "name-place", "محامي في {place}: {name}", "עורך דין ב{place}: {name}", "A lawyer in {place}: {name}", "شوف المكتب", "ראו משרד", "See the office", "place"),
    T("headline", "service-name", "{service} عند المحامي {name}", "{service} אצל עורך הדין {name}", "{service} with lawyer {name}", "شوف المجال", "ראו תחום", "See the field", "service"),
    T("headline", "near-you", "قريب عليك في {place} — مكتب {name}", "קרוב ב{place} — המשרד של {name}", "Near you in {place} — {name}’s office", "شوف وين", "איפה", "See where", "place"),
    T("headline", "today", "بدك تسأل سؤال قانوني اليوم؟ {name}", "שאלה משפטית היום? {name}", "A legal question today? {name}", "اسأل من الصفحة", "שאלו", "Ask"),
    T("headline", "first", "أول استشارة مع {name} — على مهلك", "ייעוץ ראשון עם {name} — בנחת", "First consult with {name} — unhurried", "اقرأ الأسلوب", "קראו", "Read"),
    T("headline", "hours", "المكتب فاتح {hours}", "המשרד פתוח {hours}", "The office is open {hours}", "لحّق الدوام", "תספיקו", "Catch hours", "hours"),
    T("headline", "question", "وينك عن محامي؟ {name} هون", "מחפשים עורך דין? {name} כאן", "Need a lawyer? {name} is here", "كمّل", "המשיכו", "Continue"),
    T("headline", "hello", "مكتب {name} بيستقبلك", "המשרד של {name} מקבל אתכם", "{name}’s office will see you", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا {service} همّك — اسأل {name}", "אם {service} רלוונטי — שאלו את {name}", "If {service} is the issue — ask {name}", "اسأل المجال", "שאלו תחום", "Ask the field", "service"),
    T("headline", "ready", "{name} جاهز يسمع القضية", "{name} מוכן לשמוע את התיק", "{name} is ready to hear the matter", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لمكتب {name}", "צעד אחד למשרד {name}", "One step to {name}’s office", "خذ الخطوة", "צעד", "Step"),
    T("hook", "pain", "زهقت تلف ودوران؟ مكتب {name} قدامك.", "נמאס להסתובב? המשרד של {name} כאן.", "Tired of circling? {name}’s office is here.", "اسأل", "שאלו", "Ask"),
    T("hook", "neighbor", "جارك في {place} بيعرف مكتب {name}.", "השכן ב{place} מכיר את {name}.", "Your neighbor in {place} knows {name}.", "اسأل عنهم", "שאלו", "Ask around", "place"),
    T("hook", "who", "إذا بتدور {service} — صفحة {name} إلك.", "אם מחפשים {service} — העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
    T("hook", "week", "هالأسبوع فيك تحجز ربع ساعة مع {name}.", "השבוע אפשר רבע שעה עם {name}.", "This week you can book 15 minutes with {name}.", "خطّط", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: محامي {name}.", "עצרו: עורך דין {name}.", "Stop: lawyer {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب المكتب {phone}", "וואטסאפ למשרד {phone}", "WhatsApp the office {phone}", "ابعت", "שלחו", "Message", "phone"),
    T("hook", "call-easy", "اتّصل {phone} واسأل السكرتيرة", "התקשרו {phone} למזכירות", "Call {phone} and ask the desk", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم مكتب: {name}.", "השם משרד: {name}.", "The name is an office: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للاستشارة.", "{name} — מהקישור לייעוץ.", "{name} — from the link to a consult.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم تيه: روح على مكتب {name}.", "בלי טפסים: למשרד {name}.", "No scavenger form: go to {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "اطلب موعد استشارة من صفحة {name}", "בקשו פגישת ייעוץ מעמוד {name}", "Request a consult on {name}’s page", "اطلب موعد", "בקשו פגישה", "Request a meeting"),
    T("cta", "call", "اتّصل {phone} واسأل عن الاستشارة", "התקשרו {phone} לייעוץ", "Call {phone} about a consult", "اتّصل للمكتب", "התקשרו למשרד", "Call the office", "phone"),
    T("cta", "consult", "اكتب سؤالك لـ {name} من الصفحة", "כתבו שאלה ל{name} מהעמוד", "Write your question to {name}", "اكتب السؤال", "כתבו שאלה", "Write the question"),
    T("cta", "map", "المكتب في {place}: {name}", "המשרד ב{place}: {name}", "The office in {place}: {name}", "افتح الخريطة", "פתחו מפה", "Open the map", "place"),
    T("cta", "wa", "واتساب المحامي {phone}", "וואטסאפ לעורך הדין {phone}", "WhatsApp the lawyer {phone}", "واتساب المكتب", "וואטסאפ למשרד", "WhatsApp office", "phone"),
    T("cta", "ask-service", "أكّد إذا بياخدوا ملفات {service}", "אשרו אם הם לוקחים תיקי {service}", "Confirm they take {service} files", "أكّد الملف", "אשרו תיק", "Confirm the file", "service"),
    T("cta", "visit-site", "زور صفحة مكتب {name}", "בקרו בעמוד המשרד של {name}", "Visit {name}’s office page", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ رقم المكتب — صفحة {name}", "שמרו את עמוד {name}", "Save {name}’s page", "احفظ", "שמרו", "Save"),
    T("cta", "write", "ابعِت كلمة إنك بدك استشارة", "כתבו שאתם צריכים ייעוץ", "Write that you need a consult", "ابعت", "שלחו", "Send"),
    T("cta", "open-now", "افتح مكتب {name} هسا", "פתחו את משרד {name} עכשיו", "Open {name}’s office now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "دوام المكتب: {hours}.", "שעות המשרד: {hours}.", "Office hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الاستشارة من رابط {name}.", "בלי סיבוב — הייעוץ מקישור {name}.", "No maze — the consult is on {name}’s link.", "كمّل", "המשיכו", "Follow"),
    T("headline", "family", "اسأل {name} قبل ما تمضي ورقة", "שאלו את {name} לפני שחותמים", "Ask {name} before you sign", "اسأل قبل التوقيع", "שאלו לפני חתימה", "Ask before signing"),
    T("cta", "photos", "ابعِت صورة العقد لـ {name}", "שלחו צילום חוזה ל{name}", "Send the contract photo to {name}", "ابعت العقد", "שלחו חוזה", "Send the contract"),
  ],
};
