import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const medicalClinics: NicheDefinition = {
  id: "medical_clinics",
  labels: { ar: "عيادات طبية", he: "מרפאות", en: "Medical clinics" },
  keywords: [
    "عيادة",
    "طبيب",
    "طبيبة",
    "دكتور",
    "د.",
    "عائلة",
    "طبيب عام",
    "طبيبة عامة",
    "باطنية",
    "family doctor",
    "gp clinic",
    "clinic",
    "מרפאה",
    "רופא",
    "רופאת",
    "רופא משפחה",
    "כללית",
    "كلاليت",
    "مكابي",
    "مقابي",
    "leumit",
    "مؤمني",
    "فحص",
    "وصفة",
  ],
  strongKeywords: ["طبيب عام", "طبيب عائلة", "عيادة طبية", "family doctor", "רופא משפחה"],
  vetoKeywords: [
    "أسنان",
    "اسنان",
    "dental",
    "dentist",
    "שיניים",
    "صالون",
    "مقاول",
    "مطعم",
    "طب الأطفال",
    "طبيب أطفال",
    "pediatric",
    "מרפאת ילדים",
    "عيادة أطفال",
  ],
  scanPriority: ["name", "phone", "place", "hours", "services", "whatsapp"],
  ctaStyle: "whatsapp_or_call",
  serviceCatalog: [
    "فحص",
    "وصفات",
    "استشارة",
    "طب عائلة",
    "family medicine",
    "consult",
  ],
  stockQueries: [
    "family doctor consult no text",
    "general clinic waiting room calm",
    "child health checkup warm light",
    "clinic reception local",
    "stethoscope desk not hospital emergency",
  ],
  motifs: [
    motif("mc1", "waiting", "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&q=80", ["clinic hallway"], "ممر {name}", "מסדרון {name}", "{name} hallway"),
    motif("mc2", "consult", "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=900&q=80", ["doctor consult"], "جلسة {name}", "ייעוץ {name}", "{name} consult"),
    motif("mc3", "care", "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80", ["care"], "رعاية {name}", "טיפול {name}", "{name} care"),
    motif("mc4", "team", "https://images.unsplash.com/photo-1551076805-e1869033e561?w=900&q=80", ["clinic team"], "ناس {name}", "צוות {name}", "{name} team"),
    motif("mc5", "calm", "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=900&q=80", ["calm clinic"], "هدوء {name}{place}", "שקט {name}", "calm {name}"),
    motif("mc6", "light", "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=900&q=80", ["clinic light"], "ضوء {name}", "אור {name}", "{name} light"),
    motif("mc7", "reception", "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=900&q=80", ["reception"], "استقبال {name}", "קבלה {name}", "{name} reception"),
    motif("mc8", "family", "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&q=80", ["family clinic"], "عيلة عند {name}", "משפחה אצל {name}", "family at {name}"),
    motif("mc9", "desk", "https://images.unsplash.com/photo-1579684453423-f84349ef60b0?w=900&q=80", ["clinic desk"], "مكتب {name}", "שולחן {name}", "{name} desk"),
  ],
  copy: [
    T("headline", "name-only", "هاي {name}", "זה {name}", "This is {name}", "ادخل شوف", "כנסו לראות", "Come see"),
    T("headline", "name-place", "{name} في {place}", "{name} ב{place}", "{name} in {place}", "شوف العيادة", "ראו את המרפאה", "See the clinic", "place"),
    T("headline", "near-you", "قريب عليك في {place}: {name}", "קרוב אליכם ב{place}: {name}", "Near you in {place}: {name}", "شوف وين", "בדקו איפה", "See where", "place"),
    T("headline", "first", "أول زيارة لـ {name} — على مهلك", "ביקור ראשון אצל {name} — בנחת", "First visit to {name} — at your pace", "احجز من الصفحة", "קבעו מהעמוד", "Book from the page"),
    T("headline", "question", "وينك عن {name}؟", "איפה הייתם מ{name}?", "Where have you been — {name} is here", "تعالا شوف", "בואו תראו", "Come have a look"),
    T("headline", "today", "بدك تخلّص الفحص اليوم مع {name}؟", "רוצים לסגור בדיקה היום עם {name}?", "Want the checkup today with {name}?", "يلا من الصفحة", "יאללה מהעמוד", "Go from the page"),
    T("headline", "hours", "{name} فاتح {hours}", "{name} פתוח {hours}", "{name} is open {hours}", "لحّق الدوام", "תספיקו לשעות", "Catch the hours", "hours"),
    T("headline", "service-name", "{service} عند {name}", "{service} אצל {name}", "{service} at {name}", "شوف الخدمة", "ראו את השירות", "See the service", "service"),
    T("headline", "usp-service", "إذا {service} همّك — {name} هون", "אם {service} רלוונטי — {name} כאן", "If {service} is what you need — {name} is here", "كمّل قراءة", "המשיכו לקרוא", "Keep reading", "service"),
    T("headline", "family", "خد أهلك على {name}", "קחו את המשפחה ל{name}", "Bring the family to {name}", "احكي مع العيلة", "דברו בבית", "Talk at home"),
    T("headline", "calm-clinic", "عيادة تمشي على مهلك: {name}", "מרפאה שעובדת בנחת: {name}", "A clinic that takes its time: {name}", "شوف الأسلوب", "ראו סגנון", "See the style"),
    T("headline", "hello", "مرحبا في {name}", "ברוכים הבאים ל{name}", "Welcome to {name}", "أهلاً", "שלום", "Hello"),
    T("hook", "pain", "زهقت تدور عيادة؟ {name} قدامك.", "נמאס לחפש מרפאה? {name} מולכם.", "Tired of hunting a clinic? {name} is right here.", "اسأل من الصفحة", "שאלו מהעמוד", "Ask on the page"),
    T("hook", "neighbor", "جارك في {place} بمرّق على {name}.", "השכן ב{place} כבר מכיר את {name}.", "Your neighbor in {place} already knows {name}.", "اسأل عن المواعيد", "שאלו על תורים", "Ask about times", "place"),
    T("hook", "who", "إذا بتدور {service} — صفحة {name} إلك.", "אם אתם מחפשים {service} — העמוד של {name} בשבילכם.", "Looking for {service}? {name}’s page is for you.", "اختار الخدمة", "בחרו שירות", "Pick a service", "service"),
    T("hook", "week", "هالأسبوع فيك تمرّ على {name}.", "השבוע אפשר לעבור ב{name}.", "This week you can stop by {name}.", "خطّط الزيارة", "תכננו ביקור", "Plan a visit"),
    T("hook", "scroll", "وقّف السكرول: {name}.", "עצרו את הגלילה: {name}.", "Stop the scroll: {name}.", "كمّل للإعلان", "המשיכו למודעה", "Continue to the ad"),
    T("hook", "whatsapp", "ابعت واتساب لـ {name}: {phone}", "שלחו וואטסאפ ל{name}: {phone}", "WhatsApp {name}: {phone}", "ابعت هسا", "שלחו עכשיו", "Message now", "phone"),
    T("hook", "call-easy", "اتّصل على {phone} واسأل {name}.", "התקשרו ל{phone} ושאלו את {name}.", "Call {phone} and ask {name}.", "اتّصل هسا", "התקשרו עכשיו", "Call now", "phone"),
    T("hook", "hours-hook", "دوام {name}: {hours}.", "שעות {name}: {hours}.", "{name} hours: {hours}.", "راجع الدوام", "בדקו שעות", "Check hours", "hours"),
    T("hook", "clear", "الاسم واضح: {name}.", "השם ברור: {name}.", "The name is clear: {name}.", "تأكّد من الاسم", "וודאו שם", "Confirm the name"),
    T("hook", "simple", "{name} — خطوة وحدة من الرابط.", "{name} — צעד אחד מהקישור.", "{name} — one step from the link.", "خذ الخطوة", "עשו את הצעד", "Take the step"),
    T("cta", "book", "احجز موعدك من صفحة {name}", "קבעו תור מעמוד {name}", "Book from {name}’s page", "احجز موعد", "קבעו תור", "Book a visit"),
    T("cta", "call", "اتّصل {phone} واسأل أقرب وقت", "התקשרו {phone} לשעה פנויה", "Call {phone} for the next opening", "اتّصل للموعد", "התקשרו לתור", "Call for a slot", "phone"),
    T("cta", "consult", "اطلب استشارة من {name}", "בקשו ייעוץ מ{name}", "Ask {name} for a consult", "اطلب استشارة", "בקשו ייעוץ", "Request a consult"),
    T("cta", "map", "افتح الخريطة لـ {name} في {place}", "פתחו מפה ל{name} ב{place}", "Open the map for {name} in {place}", "افتح الخريطة", "פתחו מפה", "Open the map", "place"),
    T("cta", "wa", "واتساب العيادة {phone}", "וואטסאפ למרפאה {phone}", "WhatsApp the clinic {phone}", "واتساب العيادة", "וואטסאפ למרפאה", "WhatsApp clinic", "phone"),
    T("cta", "ask-service", "اسأل عن {service} قبل ما تقرّر", "שאלו על {service} לפני שמחליטים", "Ask about {service} before you decide", "اسأل قبل القرار", "שאלו קודם", "Ask first", "service"),
    T("cta", "visit-site", "زور موقع {name}", "בקרו באתר של {name}", "Visit {name}’s site", "زور الموقع", "בקרו באתר", "Visit the site"),
    T("cta", "save", "احفظ صفحة {name} لبعدين", "שמרו את העמוד של {name}", "Save {name}’s page for later", "احفظ الصفحة", "שמרו עמוד", "Save the page"),
    T("cta", "write", "اكتبلهم كلمة على صفحة {name}", "כתבו מילה בעמוד של {name}", "Leave a note on {name}’s page", "اكتب كلمة", "כתבו מילה", "Write a note"),
    T("cta", "open-now", "افتح {name} بهاللحظة", "פתחו את {name} ברגע זה", "Open {name} this moment", "افتح هاللحظة", "פתחו ברגע", "Open this moment"),
    T("headline", "ready", "{name} جاهز يسمعك", "{name} מוכן לשמוע", "{name} is ready to hear you", "احكي هسا", "דברו עכשיו", "Talk now"),
    T("headline", "one-step", "خطوة وحدة توصلّك لـ {name}", "צעד אחד אל {name}", "One step to {name}", "خذ الخطوة", "צעד", "Take a step"),
    T("hook", "no-form", "ما في لف ودوران — {name} من الرابط.", "בלי סיבובים — {name} מהקישור.", "No runaround — {name} from the link.", "كمّل الرابط", "המשיכו בקישור", "Follow the link"),
    T("hook", "direct", "بلا فورم تيه: روح على {name}.", "בלי טפסים: לכו ל{name}.", "No scavenger form: go to {name}.", "روح للصفحة", "לעמוד", "Go to the page"),
  ],
};
