import type { OutOfNicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const outOfNiche: OutOfNicheDefinition = {
  id: "out_of_niche",
  labels: { ar: "برّا التخصص", he: "מחוץ לתחום", en: "Outside our niches" },
  keywords: [],
  scanPriority: ["name", "phone", "place", "hours", "whatsapp", "services"],
  ctaStyle: "whatsapp_or_call",
  serviceCatalog: [],
  forbiddenHooks: [
    "عيادة هادية",
    "موجوع؟",
    "كرسي الأسنان",
    "احجز طاولة",
    "مقاول",
    "حصة يوغا",
    "تقويم",
    "تبييض",
  ],
  stockQueries: ["local shop storefront", "small office desk", "street business"],
  motifs: [
    motif("o1", "desk", "https://images.unsplash.com/photo-1497366216548-37526070297c?w=900&q=80", ["desk"], "مكتب {name}", "שולחן {name}", "{name} desk"),
    motif("o2", "street", "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=900&q=80", ["street"], "واجهة {name}{place}", "חזית {name}", "{name} front"),
    motif("o3", "work", "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=900&q=80", ["work"], "شغل {name}", "עבודה {name}", "{name} work"),
    motif("o4", "people", "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=900&q=80", ["people"], "وجوه {name}", "אנשים {name}", "{name} people"),
    motif("o5", "plan", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80", ["plan"], "خطة {name}", "תוכנית {name}", "{name} plan"),
    motif("o6", "screen", "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&q=80", ["screen"], "شاشة {name}", "מסך {name}", "{name} screen"),
    motif("o7", "office", "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=900&q=80", ["office"], "نهار {name}", "יום {name}", "{name} day"),
    motif("o8", "room", "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=900&q=80", ["room"], "غرفة {name}", "חדר {name}", "{name} room"),
    motif("o9", "shop", "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80", ["shop"], "محل {name}", "חנות {name}", "{name} shop"),
  ],
  copy: [
    T("headline", "name-only", "هاي {name}", "זה {name}", "This is {name}", "افتح الصفحة", "פתחו עמוד", "Open the page"),
    T("headline", "name-place", "{name} في {place}", "{name} ב{place}", "{name} in {place}", "شوف وين", "איפה", "See where", "place"),
    T("headline", "generic", "اللي ظاهر على صفحتهم: {name}", "מה שכתוב אצלם: {name}", "What’s on their page: {name}", "اقرأ الصفحة", "קראו", "Read the page"),
    T("headline", "hello", "مرحبا في {name}", "ברוכים הבאים ל{name}", "Welcome to {name}", "أهلاً", "שלום", "Hello"),
    T("headline", "question", "وينك عن {name}؟", "איפה הייתם מ{name}?", "Where have you been — {name}", "تعالا شوف", "בואו", "Come see"),
    T("headline", "ready", "{name} جاهز يسمعك", "{name} מוכן לשמוע", "{name} is ready to hear you", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة توصلّك لـ {name}", "צעד אחד אל {name}", "One step to {name}", "خذ الخطوة", "צעד", "Step"),
    T("headline", "open-page", "صفحة {name} جاهزة إلك", "העמוד של {name} מוכן", "{name}’s page is ready", "افتح هسا", "פתחו", "Open now"),
    T("headline", "host-name", "{name}", "{name}", "{name}", "اقرأ المزيد", "קראו עוד", "Read more"),
    T("hook", "soft-out", "{name}: اللي ظاهر على صفحتهم، وبس.", "{name}: רק מה שכתוב אצלם.", "{name}: only what their page shows.", "اقرأ الصفحة", "קראו את העמוד", "Read the page"),
    T("hook", "pain", "زهقت تدور؟ {name} قدامك — من غير تخصص ملفّق.", "נמאס לחפש? {name} כאן — בלי נישה מומצאת.", "Tired of hunting? {name} is here — no fake specialty.", "اسأل من الصفحة", "שאלו", "Ask"),
    T("hook", "scroll", "وقّف السكرول: {name}.", "עצרו: {name}.", "Stop: {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "clear", "الاسم واضح: {name}.", "השם ברור: {name}.", "The name is clear: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — خطوة وحدة من الرابط.", "{name} — צעד אחד מהקישור.", "{name} — one step from the link.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم تيه: روح على {name}.", "בלי טפסים: לכו ל{name}.", "No scavenger form: go to {name}.", "روح للصفحة", "לעמוד", "Go to the page"),
    T("hook", "no-form", "ما في لف ودوران — {name} من الرابط.", "בלי סיבובים — {name} מהקישור.", "No runaround — {name} from the link.", "كمّل الرابط", "המשיכו", "Follow the link"),
    T("hook", "neighbor", "إذا أنت في {place} — {name} مذكور هون.", "אם אתם ב{place} — {name} מופיע כאן.", "If you’re in {place} — {name} is listed here.", "شوف المكان", "ראו מקום", "See the place", "place"),
    T("hook", "whatsapp", "راسل {name} على {phone}", "כתבו ל{name} ב{phone}", "Message {name} at {phone}", "راسل المحل", "כתבו לעסק", "Message the business", "phone"),
    T("hook", "call-easy", "اتّصل {phone}", "התקשרו {phone}", "Call {phone}", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "hours-hook", "دوام {name}: {hours}.", "שעות {name}: {hours}.", "{name} hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("cta", "book", "تواصل مع {name} من موقعهم", "צרו קשר עם {name} מהאתר", "Contact {name} from their site", "تواصل من الموقع", "צרו קשר", "Get in touch"),
    T("cta", "call", "اتّصل {phone}", "התקשרו {phone}", "Call {phone}", "اتّصل", "התקשרו", "Call", "phone"),
    T("cta", "read", "اقرأ وصف {name}", "קראו את התיאור של {name}", "Read {name}’s description", "اقرأ الوصف", "קראו תיאור", "Read the description"),
    T("cta", "map", "دور على {name} في {place}", "חפשו את {name} ב{place}", "Find {name} in {place}", "ابحث بالمكان", "חפשו במקום", "Search the place", "place"),
    T("cta", "wa", "راسل {name} على {phone}", "כתבו ל{name} ב{phone}", "Message {name} at {phone}", "راسل المحل", "כתבו לעסק", "Message the business", "phone"),
    T("cta", "site", "ارجع لرابط {name}", "חזרו לקישור של {name}", "Return to {name}’s link", "افتح الرابط", "פתחו קישור", "Open the link"),
    T("cta", "visit-site", "زور موقع {name}", "בקרו באתר של {name}", "Visit {name}’s site", "زور الموقع", "בקרו באתר", "Visit the site"),
    T("cta", "save", "احفظ صفحة {name} لبعدين", "שמרו את העמוד של {name}", "Save {name}’s page for later", "احفظ الصفحة", "שמרו עמוד", "Save the page"),
    T("cta", "write", "اكتبلهم كلمة على صفحة {name}", "כתבו מילה בעמוד של {name}", "Leave a note on {name}’s page", "اكتب كلمة", "כתבו מילה", "Write a note"),
    T("cta", "open-now", "افتح {name} بهاللحظة", "פתחו את {name} ברגע זה", "Open {name} this moment", "افتح هاللحظة", "פתחו ברגע", "Open this moment"),
    T("headline", "today", "بدك تخلّصها اليوم مع {name}؟", "רוצים לסגור את זה היום עם {name}?", "Want this done today with {name}?", "يلا من الصفحة", "יאללה", "Go from the page"),
    T("cta", "ask-page", "اسأل {name} سؤال واحد", "שאלו את {name} שאלה אחת", "Ask {name} one question", "اسأل سؤال", "שאלו שאלה", "Ask one question"),
    T("hook", "more", "في تفاصيل زيادة عن {name} على الصفحة.", "יש עוד פרטים על {name} בעמוד.", "More about {name} is on the page.", "زِد قراءة", "קראו עוד", "Read a bit more"),
    T("cta", "go", "كمّل لصفحة {name}", "המשיכו לעמוד {name}", "Continue to {name}", "كمّل", "המשיכו", "Continue"),
    T("headline", "first", "أول مرة تشوف {name} — من صفحتهم", "פעם ראשונה עם {name} — מהעמוד", "First time seeing {name} — from their page", "اقرأ", "קראו", "Read"),
    T("hook", "who", "إذا الاسم {name} — هاي صفحتهم.", "אם השם {name} — זה העמוד.", "If the name is {name} — this is their page.", "تأكّد", "וודאו", "Confirm"),
  ],
};
