import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const pediatricClinics: NicheDefinition = {
  id: "pediatric_clinics",
  labels: { ar: "عيادات أطفال", he: "מרפאות ילדים", en: "Pediatric clinics" },
  keywords: [
    "طب الأطفال",
    "طبيب أطفال",
    "طبيبة أطفال",
    "عيادة أطفال",
    "عيادة الاطفال",
    "عيادة الأطفال",
    "أطفال",
    "اطفال",
    "رضيع",
    "حديثي الولادة",
    "pediatric",
    "paediatric",
    "pediatrics",
    "child clinic",
    "children clinic",
    "kids clinic",
    "מרפאת ילדים",
    "רופא ילדים",
    "רופאת ילדים",
    "ילדים",
    "תינוק",
    "drsamerped",
    "samerped",
  ],
  strongKeywords: [
    "طب الأطفال",
    "طبيب أطفال",
    "عيادة أطفال",
    "pediatric",
    "מרפאת ילדים",
    "רופא ילדים",
    "drsamerped",
    "عيادتي",
  ],
  vetoKeywords: ["أسنان", "dental", "صالون", "مقاول", "مطعم", "محامي"],
  scanPriority: ["name", "whatsapp", "phone", "place", "services", "hours"],
  ctaStyle: "whatsapp",
  forbiddenHooks: ["كرسي الأسنان", "احجز طاولة", "مقاول", "تبييض"],
  serviceCatalog: [
    "فحص أطفال",
    "متابعة نمو",
    "تطعيم",
    "وصفات",
    "استشارة أطفال",
    "pediatric",
    "vaccination",
    "בדיקת ילדים",
    "חיסון",
    "كلاليت",
    "כללית",
  ],
  stockQueries: [
    "pediatric clinic waiting room toys warm",
    "parent and child doctor consult calm",
    "child health checkup no text",
    "friendly kids clinic reception",
    "stethoscope child visit not emergency",
  ],
  motifs: [
    motif("p1", "waiting", "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=900&q=80", ["kids waiting"], "انتظار الأطفال — {name}", "חדר המתנה לילדים — {name}", "kids waiting — {name}"),
    motif("p2", "consult", "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80", ["child consult"], "فحص ولد عند {name}", "בדיקת ילד אצל {name}", "child visit at {name}"),
    motif("p3", "care", "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&q=80", ["parent care"], "أم وولد عند {name}", "אמא וילד אצל {name}", "parent and child at {name}"),
    motif("p4", "calm", "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=900&q=80", ["calm pediatrics"], "هدوء عيادة الأطفال {name}", "שקט במרפאת הילדים {name}", "calm pediatric {name}"),
    motif("p5", "team", "https://images.unsplash.com/photo-1551076805-e1869033e561?w=900&q=80", ["pedia team"], "ناس {name}", "צוות {name}", "{name} team"),
    motif("p6", "light", "https://images.unsplash.com/photo-1666214280557-f1b5022eb634?w=900&q=80", ["soft light"], "ضوء {name}{place}", "אור {name}", "{name} light"),
    motif("p7", "reception", "https://images.unsplash.com/photo-1516549655169-df83a0774514?w=900&q=80", ["reception"], "استقبال عيادتي — {name}", "קבלה — {name}", "reception — {name}"),
    motif("p8", "desk", "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=900&q=80", ["doctor desk"], "مكتب {doctor}", "שולחן {doctor}", "{doctor} desk"),
    motif("p9", "toys", "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=900&q=80", ["play corner"], "ركن الألعاب — {name}", "פינת משחק — {name}", "play corner — {name}"),
  ],
  copy: [
    T("headline", "name-only", "هاي عيادتي — {name}", "זו המרפאה שלי — {name}", "This is my clinic — {name}", "ادخل شوف", "כנסו", "Come see"),
    T("headline", "name-place", "{name} في {place} — عيادة أطفال", "{name} ב{place} — מרפאת ילדים", "{name} in {place} — pediatric clinic", "شوف وين", "איפה", "See where", "place"),
    T("headline", "doctor", "{doctor} في عيادتي", "{doctor} במרפאה שלי", "{doctor} at my clinic", "تعرّف عالدكتور", "הכירו את הרופא", "Meet the doctor", "doctor"),
    T("headline", "near-you", "أمّهات {place}: {name} قريبة عليكي", "אימהות ב{place}: {name} קרובה", "Mums in {place}: {name} is nearby", "شوف المكان", "ראו מקום", "See the place", "place"),
    T("headline", "today", "الولد سخن؟ عيادتي {name} بتسمعك اليوم", "הילד חם? {name} שומעת היום", "Fever today? {name} will hear you", "احجزي واتساب", "קבעו בוואטסאפ", "Book on WhatsApp"),
    T("headline", "first", "أول زيارة لأطفالك عند {name} — على مهلك", "ביקור ראשון לילדים אצל {name}", "First kids’ visit at {name} — unhurried", "اقرئي الأسلوب", "קראו", "Read"),
    T("headline", "hours", "{name} فاتحة {hours}", "{name} פתוחה {hours}", "{name} is open {hours}", "لحّقي الدوام", "תספיקו", "Catch hours", "hours"),
    T("headline", "hello", "أهلا في عيادتي", "ברוכות הבאות למרפאה שלי", "Welcome to my clinic", "أهلاً", "שלום", "Hello"),
    T("headline", "service-name", "{service} لأطفالك عند {name}", "{service} לילדים אצל {name}", "{service} for your kids at {name}", "شوف الخدمة", "ראו שירות", "See the service", "service"),
    T("headline", "usp-slogan", "{slogan} — هاي {name}، مش الاسم", "{slogan} — זה {name}, לא השם", "{slogan} — that’s {name}, not the name", "اقرئي الوصف", "קראו תיאור", "Read the line", "slogan"),
    T("headline", "ready", "عيادتي جاهزة تسمع قلق الأم", "המרפאה שלי מוכנה לשמוע את האמא", "My clinic is ready to hear the mum", "احكي", "דברי", "Talk"),
    T("headline", "one-step", "خطوة وحدة لموعد أطفال عند {name}", "צעד אחד לתור ילדים אצל {name}", "One step to a kids’ slot at {name}", "خذ الخطوة", "צעד", "Step"),
    T("hook", "pain", "الليل طويل والولد موجوع؟ واتساب {name} قدامك.", "לילה ארוך והילד כואב? הוואטסאפ של {name} כאן.", "Long night and a hurting child? {name}’s WhatsApp is here.", "ابعتي هسا", "שלחו עכשיו", "Message now"),
    T("hook", "worry", "قلبك مش مرتاح على الحرارة؟ اسألي {name}.", "הלב לא שקט על החום? שאלי את {name}.", "Uneasy about the fever? Ask {name}.", "اسألي", "שאלי", "Ask"),
    T("hook", "neighbor", "أم جارتك في {place} بتمرّق على {name}.", "השכנה ב{place} כבר אצל {name}.", "A mum next door in {place} already goes to {name}.", "اسألي عنهم", "שאלי", "Ask around", "place"),
    T("hook", "who", "بتدورّي {service} لطفلك؟ صفحة {name} إلك.", "מחפשת {service} לילד? העמוד של {name}.", "Looking for {service} for your child? {name}’s page.", "اختاري", "בחרי", "Pick", "service"),
    T("hook", "week", "هالأسبوع فيكي تحجزي فحص ولد عند {name}.", "השבוע אפשר לקבוע בדיקת ילד אצל {name}.", "This week you can book a child checkup at {name}.", "خطّطي", "תכנני", "Plan"),
    T("hook", "scroll", "وقّفي السكرول: عيادة أطفال {name}.", "עצרי: מרפאת ילדים {name}.", "Stop: pediatric clinic {name}.", "كمّلي", "המשיכי", "Continue"),
    T("hook", "whatsapp", "واتساب الحجز لـ {name}: {phone}", "וואטסאפ לקביעת תור אצל {name}: {phone}", "WhatsApp booking for {name}: {phone}", "احجزي واتساب", "קבעו בוואטסאפ", "Book on WhatsApp", "phone"),
    T("hook", "call-easy", "اتّصلي {phone} واسألي أقرب دور لولدك", "התקשרי {phone} לתור לילד", "Call {phone} for the next kids’ slot", "اتّصلي", "התקשרי", "Call", "phone"),
    T("hook", "clear", "الاسم عيادتي: {name}. الشعار مش الاسم.", "השם המרפאה שלי: {name}. הסלוגן לא השם.", "The name is my clinic: {name}. The slogan is not the name.", "تأكّدي", "וודאי", "Confirm"),
    T("hook", "simple", "{name} — من الرابط لموعد الولد.", "{name} — מהקישור לתור הילד.", "{name} — from the link to the child’s slot.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: احجزي لولدك عند {name}.", "בלי טפסים: קבעי לילד אצל {name}.", "No form: book your child at {name}.", "روحي", "לכי", "Go"),
    T("hook", "usp-slogan", "الوصف على الصفحة: {slogan}. الاسم {name}.", "התיאור בעמוד: {slogan}. השם {name}.", "On-page USP: {slogan}. The name is {name}.", "اقرئي", "קראי", "Read", "slogan"),
    T("cta", "book", "احجزي موعد أطفال واتساب من صفحة {name}", "קבעי תור ילדים בוואטסאפ מעמוד {name}", "Book a kids’ slot on WhatsApp from {name}", "احجزي واتساب", "קבעי בוואטסאפ", "Book on WhatsApp"),
    T("cta", "call", "اتّصلي {phone} لدور الولد", "התקשרי {phone} לתור הילד", "Call {phone} for the child’s turn", "اتّصلي للموعد", "התקשרי לתור", "Call for a slot", "phone"),
    T("cta", "wa", "واتساب عيادتي {phone}", "וואטסאפ למרפאה שלי {phone}", "WhatsApp my clinic {phone}", "واتساب الحجز", "וואטסאפ לקביעה", "WhatsApp booking", "phone"),
    T("cta", "consult", "اسألي {doctor} عن حرارة أو سعال", "שאלי את {doctor} על חום או שיעול", "Ask {doctor} about fever or a cough", "اسألي الدكتور", "שאלי את הרופא", "Ask the doctor", "doctor"),
    T("cta", "map", "عيادة الأطفال في {place}: {name}", "מרפאת הילדים ב{place}: {name}", "The pediatric clinic in {place}: {name}", "افتحي الخريطة", "פתחי מפה", "Open the map", "place"),
    T("cta", "insurance", "اسألي إذا {insurance} يغطي الفحص عند {name}", "שאלי אם {insurance} מכסה אצל {name}", "Ask if {insurance} covers a visit at {name}", "اسألي التأمين", "שאלי ביטוח", "Ask insurance", "insurance"),
    T("cta", "ask-service", "أكّدي إنهم بعملوا {service} للولد", "אשרי שהם עושים {service} לילד", "Confirm they do {service} for kids", "أكّدي", "אשרי", "Confirm", "service"),
    T("cta", "visit-site", "زوري صفحة عيادتي {name}", "בקרי בעמוד המרפאה {name}", "Visit my clinic page {name}", "زوري", "בקרי", "Visit"),
    T("cta", "save", "احفظي واتساب {name} لليلة", "שמרי את הוואטסאפ של {name} ללילה", "Save {name}’s WhatsApp for tonight", "احفظي", "שמרי", "Save"),
    T("cta", "write", "اكتبي: بدّي موعد لولدي عند {name}", "כתבי: צריכה תור לילד אצל {name}", "Write: I need a kids’ slot at {name}", "اكتبي", "כתבי", "Write"),
    T("cta", "open-now", "افتحي عيادتي {name} هسا", "פתחי את {name} עכשיו", "Open {name} now", "افتحي", "פתחי", "Open"),
    T("hook", "hours-hook", "دوام عيادة الأطفال: {hours}.", "שעות מרפאת הילדים: {hours}.", "Pediatric hours: {hours}.", "راجعي", "בדקי", "Check", "hours"),
    T("hook", "no-form", "ما في لف — موعد الولد من رابط {name}.", "בלי סיבוב — תור הילד מקישור {name}.", "No maze — the child’s slot is on {name}’s link.", "كمّلي", "המשיכי", "Follow"),
    T("headline", "family", "خدّي أخوته كمان على {name}", "קחי גם את האחים ל{name}", "Bring the siblings to {name} too", "احكي بالبيت", "דברי בבית", "Talk at home"),
    T("cta", "photos", "ابعِتي صورة الحرارة أو الدفتر لـ {name}", "שלחי צילום חום או פנקס ל{name}", "Send a fever photo or booklet to {name}", "ابعِتي صورة", "שלחי תמונה", "Send a photo"),
    T("hook", "insurance", "مكتوب عندهم {insurance} — من الصفحة، مش اختراع.", "כתוב אצלם {insurance} — מהעמוד, לא המצאה.", "They list {insurance} — from the page, not invented.", "تأكّدي من الصفحة", "וודאי בעמוד", "Check the page", "insurance"),
  ],
};
