import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const realEstateAgents: NicheDefinition = {
  id: "real_estate_agents",
  labels: { ar: "وسطاء عقارات محليون", he: "תיווך", en: "Local real-estate agents" },
  keywords: [
    "وسيط",
    "وسطاء",
    "عقارات",
    "عقار",
    "شقة للبيع",
    "شقة للإيجار",
    "بيت للبيع",
    "تأجير",
    "real estate",
    "realtor",
    "broker",
    "for sale",
    "for rent",
    "תיווך",
    "מתווך",
    "נדלן",
    "דירה למכירה",
    "דירה להשכרה",
  ],
  strongKeywords: ["مكتب عقارات", "תיווך", "real estate agent", "شقق للبيع"],
  vetoKeywords: ["محامي فقط", "عيادة", "مطعم", "dental"],
  scanPriority: ["name", "place", "phone", "whatsapp", "services", "hours"],
  ctaStyle: "whatsapp",
  serviceCatalog: [
    "بيع",
    "إيجار",
    "شقق",
    "بيوت",
    "أراضي",
    "sale",
    "rent",
    "מכירה",
    "השכרה",
    "דירות",
  ],
  stockQueries: [
    "apartment keys in hand",
    "local house exterior daylight",
    "real estate agent door",
    "empty living room listing",
    "neighborhood street homes",
  ],
  motifs: [
    motif("re1", "keys", "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=900&q=80", ["keys"], "مفاتيح {name}", "מפתחות {name}", "{name} keys"),
    motif("re2", "house", "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80", ["house"], "بيت مع {name}", "בית עם {name}", "a house with {name}"),
    motif("re3", "street", "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&q=80", ["street"], "حي {name}{place}", "שכונה {name}", "{name} street"),
    motif("re4", "room", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=900&q=80", ["listing room"], "شقة يعرضها {name}", "דירה של {name}", "a listing from {name}"),
    motif("re5", "desk", "https://images.unsplash.com/photo-1560520031-3a4dc4e2faef?w=900&q=80", ["agent desk"], "مكتب الوسيط {name}", "משרד התיווך {name}", "{name} desk"),
    motif("re6", "door", "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=900&q=80", ["door"], "باب بيت — {name}", "דלת בית — {name}", "a door — {name}"),
    motif("re7", "sky", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80", ["home sky"], "واجهة بيت {name}", "חזית בית {name}", "{name} facade"),
    motif("re8", "plan", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80", ["plan"], "خطة {name}", "תוכנית {name}", "{name} plan"),
    motif("re9", "people", "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=900&q=80", ["handover"], "تسليم مفتاح — {name}", "מסירת מפתח — {name}", "key handover — {name}"),
  ],
  copy: [
    T("headline", "name-only", "هاي وسيط {name}", "זה המתווך {name}", "This is agent {name}", "شوف المكتب", "ראו משרד", "See the office"),
    T("headline", "name-place", "تياوُك في {place}: {name}", "תיווך ב{place}: {name}", "Local listings in {place}: {name}", "شوف المنطقة", "ראו אזור", "See the area", "place"),
    T("headline", "service-name", "{service} مع الوسيط {name}", "{service} עם המתווך {name}", "{service} with agent {name}", "شوف الخدمة", "ראו שירות", "See the service", "service"),
    T("headline", "near-you", "بدك بيت في {place}؟ {name} هون", "מחפשים בית ב{place}? {name} כאן", "Looking in {place}? {name} is here", "اسأل", "שאלו", "Ask", "place"),
    T("headline", "today", "بدك تشوف بيت اليوم مع {name}؟", "לראות בית היום עם {name}?", "See a place today with {name}?", "يلا رتب", "יאללה", "Go"),
    T("headline", "first", "أول جولة عقارية مع {name} — على مهلك", "סיור ראשון עם {name}", "First viewing with {name} — unhurried", "اقرأ", "קראו", "Read"),
    T("headline", "hours", "{name} بيرد {hours}", "{name} זמין {hours}", "{name} answers {hours}", "لحّق", "תספיקו", "Catch", "hours"),
    T("headline", "question", "وينك عن شقة؟ اسأل {name}", "איפה דירה? שאלו את {name}", "Where’s a flat? Ask {name}", "اسأل", "שאלו", "Ask"),
    T("headline", "hello", "مكتب عقارات {name}", "משרד תיווך {name}", "{name} real-estate desk", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا {service} قصدك — {name} مكتوب عنده", "אם {service} רלוונטי — זה אצל {name}", "If you mean {service} — {name} lists it", "تأكّد", "וודאו", "Confirm", "service"),
    T("headline", "ready", "{name} جاهز يفتحلك باب", "{name} מוכן לפתוח דלת", "{name} is ready to open a door", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لمكتب {name}", "צעד אחד למשרד {name}", "One step to {name}’s desk", "خذ الخطوة", "צעד", "Step"),
    T("hook", "pain", "زهقت تدور شقق لحالك؟ {name} قدامك.", "נמאס לחפש דירות לבד? {name} כאן.", "Tired of hunting flats alone? {name} is here.", "اسأل", "שאלו", "Ask"),
    T("hook", "neighbor", "جارك في {place} باع أو أجّر عن طريق {name}.", "השכן ב{place} סגר עם {name}.", "A neighbor in {place} closed with {name}.", "اسأل عنهم", "שאלו", "Ask around", "place"),
    T("hook", "who", "بتدور {service}؟ صفحة {name} إلك.", "מחפשים {service}? העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
    T("hook", "week", "هالأسبوع فيك تطلب جولة مع {name}.", "השבוע אפשר סיור עם {name}.", "This week you can request a viewing with {name}.", "خطّط", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: وسيط {name}.", "עצרו: מתווך {name}.", "Stop: agent {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب الوسيط {phone}", "וואטסאפ למתווך {phone}", "WhatsApp the agent {phone}", "ابعت", "שלחו", "Message", "phone"),
    T("hook", "call-easy", "اتّصل {phone} واسأل شو نازل", "התקשרו {phone} מה יצא", "Call {phone} and ask what’s listed", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم وسيط: {name}.", "השם מתווך: {name}.", "The name is an agent: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للمفتاح.", "{name} — מהקישור למפתח.", "{name} — from the link to the key.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: احكي مع {name}.", "בלי טפסים: דברו עם {name}.", "No form: talk to {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "اطلب جولة بيت من صفحة {name}", "בקשו סיור מעמוד {name}", "Request a viewing on {name}’s page", "اطلب جولة", "בקשו סיור", "Request a viewing"),
    T("cta", "call", "اتّصل {phone} ووصف شو بتدور", "התקשרו {phone} ותארו מה מחפשים", "Call {phone} and describe the search", "وصف الطلب", "תארו חיפוש", "Describe the search", "phone"),
    T("cta", "consult", "ابعِت ميزانيتك لـ {name} من الصفحة", "כתבו תקציב ל{name}", "Send your budget to {name} from the page", "ابعت الرقم", "שלחו מספר", "Send the number"),
    T("cta", "map", "شقق {name} في {place}", "דירות {name} ב{place}", "{name} listings in {place}", "حدد المنطقة", "סמנו אזור", "Mark the area", "place"),
    T("cta", "wa", "واتساب العقارات {phone}", "וואטסאפ לתיווך {phone}", "WhatsApp listings {phone}", "واتساب الوسيط", "וואטסאפ מתווך", "WhatsApp agent", "phone"),
    T("cta", "ask-service", "أكّد إذا بعملوا {service}", "אשרו אם הם עושים {service}", "Confirm they handle {service}", "أكّد", "אשרו", "Confirm", "service"),
    T("cta", "visit-site", "زور إعلانات {name}", "בקרו במודעות {name}", "Visit {name}’s listings", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ مكتب {name} لبعدين", "שמרו את {name} להמשך", "Save {name} for later", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب: بدور بيت / شقة عند {name}", "כתבו: מחפש בית אצל {name}", "Write: looking for a home with {name}", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح مكتب {name} هسا", "פתחו את {name} עכשיו", "Open {name} now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "أوقات الرد: {hours}.", "שעות מענה: {hours}.", "Reply hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الجولة من رابط {name}.", "בלי סיבוב — הסיור מקישור {name}.", "No maze — the viewing is on {name}’s link.", "كمّل", "המשיכו", "Follow"),
    T("headline", "family", "خد أهلك يشوفوا البيت مع {name}", "קחו את המשפחה לראות עם {name}", "Bring the family to view with {name}", "احكي بالبيت", "דברו בבית", "Talk at home"),
    T("cta", "photos", "ابعِت رابط أو صورة العقار لـ {name}", "שלחו קישור או תמונה ל{name}", "Send a listing photo to {name}", "ابعت صورة", "שלחו תמונה", "Send a photo"),
  ],
};
