import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const restaurants: NicheDefinition = {
  id: "restaurants",
  labels: { ar: "مطاعم ومقاهي", he: "מסעדות ובתי קפה", en: "Restaurants & cafés" },
  keywords: [
    "مطعم",
    "مطاعم",
    "مقهى",
    "كافيه",
    "قهوة",
    "منسف",
    "مسخن",
    "جريل",
    "الجريل",
    "مشاوي",
    "شواء",
    "مطبخ",
    "طعام",
    "مأكولات",
    "شاورما",
    "فلافل",
    "restaurant",
    "restaurants",
    "café",
    "cafe",
    "bistro",
    "kitchen",
    "delivery",
    "قائمة الطعام",
    "menu",
    "grill",
    "grilling",
    "bbq",
    "barbecue",
    "barbeque",
    "steakhouse",
    "steak",
    "burger",
    "pizza",
    "pizzeria",
    "shawarma",
    "falafel",
    "diner",
    "eatery",
    "food",
    "מסעדה",
    "מסעדת",
    "בית קפה",
    "קפה",
    "אוכל",
    "משלוחים",
    "גריל",
    "ברביקיו",
    "בשר",
    "בשרית",
    "תפריט",
    "מטבח",
    "על האש",
    "فطور",
    "غداء",
    "عشاء",
  ],
  strongKeywords: [
    "قائمة الطعام",
    "احجز طاولة",
    "משלוחים",
    "منسف",
    "مسخن",
    "مطعم",
    "מסעדה",
    "restaurant",
    "grill",
    "גריל",
    "جريل",
    "bbq",
    "مشاوي",
    "תפריט",
  ],
  vetoKeywords: ["عيادة", "أسنان", "محامي", "مقاول", "مقاولات", "dental", "clinic", "קבלן", "שיפוץ דירה"],
  scanPriority: ["name", "place", "phone", "hours", "services", "whatsapp"],
  ctaStyle: "whatsapp",
  forbiddenHooks: ["عيادة هادية", "موجوع؟", "كرسي العلاج", "موعد طبي", "طفلك بخير", "عيادة الأسنان"],
  serviceCatalog: [
    "فطور",
    "غداء",
    "عشاء",
    "حلويات",
    "منسف",
    "مسخن",
    "قهوة",
    "مشاوي",
    "جريل",
    "breakfast",
    "delivery",
    "grill",
    "bbq",
    "משלוחים",
    "ארוחת בוקר",
    "גריל",
    "קבב",
    "תפריט",
  ],
  stockQueries: [
    "restaurant dining room warm evening",
    "plated middle eastern dish",
    "cafe counter coffee",
    "family table restaurant",
    "dessert pastry cafe",
  ],
  motifs: [
    motif("r1", "room", "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&q=80", ["dining room"], "صالة {name}{place}", "חלל {name}", "{name} room"),
    motif("r2", "coffee", "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&q=80", ["coffee"], "قهوة {name}", "קפה {name}", "{name} coffee"),
    motif("r3", "plated", "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&q=80", ["plated"], "طبق {name}", "צלחת {name}", "{name} plate"),
    motif("r4", "table", "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=900&q=80", ["table"], "طاولة {name}", "שולחן {name}", "{name} table"),
    motif("r5", "street", "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=900&q=80", ["facade"], "واجهة {name}{place}", "חזית {name}", "{name} front"),
    motif("r6", "dish", "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&q=80", ["dish"], "أكل {name}", "אוכל {name}", "{name} food"),
    motif("r7", "cafe", "https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=900&q=80", ["cafe"], "ركن {name}", "פינת {name}", "{name} corner"),
    motif("r8", "pastry", "https://images.unsplash.com/photo-1481833761820-0509d3217039?w=900&q=80", ["pastry"], "حلويات {name}", "מתוקים {name}", "{name} sweets"),
    motif("r9", "evening", "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=900&q=80", ["evening"], "مساء {name}", "ערב {name}", "{name} evening"),
  ],
  copy: [
    T("headline", "name-only", "هاي {name} — مطبخ، مش عيادة", "זה {name} — מטבח, לא מרפאה", "This is {name} — a kitchen, not a clinic", "ادخل شوف", "כנסו", "Come see"),
    T("headline", "name-place", "{name} في {place}", "{name} ב{place}", "{name} in {place}", "شوف المكان", "ראו מקום", "See the place", "place"),
    T("headline", "table", "طاولة لسا فاضية عند {name}", "עדיין יש שולחן אצל {name}", "A table still open at {name}", "احجز قبل ما تطلع", "הזמינו לפני", "Reserve first"),
    T("headline", "service-name", "{service} عند {name}", "{service} אצל {name}", "{service} at {name}", "شوف القائمة", "ראו תפריט", "See the menu", "service"),
    T("headline", "near-you", "قريب عليك في {place}: {name}", "קרוב ב{place}: {name}", "Near you in {place}: {name}", "شوف وين", "איפה", "See where", "place"),
    T("headline", "today", "بدك تتعشى اليوم عند {name}؟", "לאכול היום אצל {name}?", "Dinner today at {name}?", "يلا احجز", "יאללה", "Go"),
    T("headline", "hours", "{name} فاتح {hours}", "{name} פתוח {hours}", "{name} is open {hours}", "لحّق المطبخ", "תספיקו למטבח", "Catch the kitchen", "hours"),
    T("headline", "question", "وينك عن {name}؟", "איפה הייתם מ{name}?", "Where have you been — {name}", "تعالا ذوق", "בואו תטעמו", "Come taste"),
    T("headline", "family", "خد أهلك تتعشى عند {name}", "קחו את המשפחה לאכול אצל {name}", "Bring the family to eat at {name}", "احكي مع العيلة", "דברו בבית", "Talk at home"),
    T("headline", "hello", "أهلا في مطبخ {name}", "ברוכים הבאים למטבח {name}", "Welcome to {name}’s kitchen", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا {service} على بالك — {name} بطبخه", "אם בא {service} — {name} מבשל", "Craving {service}? {name} cooks it", "شوف الطبق", "ראו מנה", "See the dish", "service"),
    T("headline", "ready", "{name} النار شغالة", "{name} האש דולקת", "{name} has the fire on", "ادخل", "כנסו", "Come in"),
    T("hook", "craving", "جاعان على {service}؟ {name} بيستناك.", "בא לכם {service}? {name} מחכה.", "Craving {service}? {name} is waiting.", "اطلب من الصفحة", "הזמינו", "Order", "service"),
    T("hook", "pain", "زهقت تدور وين تتعشى؟ {name} قدامك.", "נמאס לחפש איפה לאכול? {name} כאן.", "Tired of hunting dinner? {name} is here.", "افتح القائمة", "פתחו תפריט", "Open the menu"),
    T("hook", "neighbor", "جارك في {place} بمرّق يتعشى عند {name}.", "השכן ב{place} אוכל אצל {name}.", "Your neighbor in {place} eats at {name}.", "اسأل المذاق", "שאלו טעם", "Ask the taste", "place"),
    T("hook", "week", "هالأسبوع فيك تحجز طاولة عند {name}.", "השבוע אפשר שולחן אצל {name}.", "This week you can book a table at {name}.", "خطّط السهرة", "תכננו ערב", "Plan the evening"),
    T("hook", "scroll", "وقّف السكرول: مطبخ {name}.", "עצרו: המטבח של {name}.", "Stop: {name}’s kitchen.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب المطعم {phone}", "וואטסאפ למסעדה {phone}", "WhatsApp the kitchen {phone}", "اطلب واتساب", "הזמינו בוואטסאפ", "Order on WhatsApp", "phone"),
    T("hook", "call-easy", "اتّصل {phone} واسأل شو فاتح بالمطبخ", "התקשרו {phone} מה פתוח במטבח", "Call {phone} and ask what’s on", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم مطبخ: {name}.", "השם מטבח: {name}.", "The name is a kitchen: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للطاولات.", "{name} — מהקישור לשולחנות.", "{name} — from the link to the tables.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: روح تعشى عند {name}.", "בלי טפסים: לכו לאכול אצל {name}.", "No form: go eat at {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "احجز طاولة عند {name}", "הזמינו שולחן אצל {name}", "Reserve a table at {name}", "احجز طاولة", "הזמינו שולחן", "Reserve a table"),
    T("cta", "call", "اتّصل {phone} واسأل شو فاتح", "התקשרו {phone} מה פתוח", "Call {phone} and ask what’s open", "اسأل الدوام", "שאלו שעות", "Ask the hours", "phone"),
    T("cta", "menu", "شوف {service} عند {name}", "ראו {service} אצל {name}", "See {service} at {name}", "شوف القائمة", "ראו תפריט", "See the menu", "service"),
    T("cta", "map", "اتجه على {name} في {place}", "נווטו ל{name} ב{place}", "Head to {name} in {place}", "خذني هناك", "קחו אותי", "Take me there", "place"),
    T("cta", "wa", "اطلب بالواتساب {phone}", "הזמינו בוואטסאפ {phone}", "Order on WhatsApp {phone}", "اطلب بالواتساب", "הזמינו בוואטסאפ", "Order on WhatsApp", "phone"),
    T("cta", "tonight", "مرّ الليلة إذا كنت بـ {place}", "עברו הערב אם אתם ב{place}", "Stop by tonight if you’re in {place}", "مرّ الليلة", "עברו הערב", "Stop by tonight", "place"),
    T("cta", "visit-site", "زور قائمة {name}", "בקרו בתפריט {name}", "Visit {name}’s menu page", "زور القائمة", "בקרו בתפריט", "See the menu page"),
    T("cta", "save", "احفظ {name} لسهرة بعدين", "שמרו את {name} לערב אחר", "Save {name} for another night", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب إنك بدك طاولة عند {name}", "כתבו שאתם צריכים שולחן אצל {name}", "Write that you want a table at {name}", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح مطبخ {name} هاللحظة", "פתחו את המטבח של {name} עכשיו", "Open {name}’s kitchen now", "افتح", "פתחו", "Open"),
    T("headline", "one-step", "خطوة وحدة توصلّك لطاولة {name}", "צעד אחד לשולחן {name}", "One step to a table at {name}", "خذ الخطوة", "צעד", "Take a step"),
    T("hook", "hours-hook", "دوام المطبخ: {hours}.", "שעות המטבח: {hours}.", "Kitchen hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الطاولة من رابط {name}.", "בלי סיבוב — השולחן מקישור {name}.", "No maze — the table is on {name}’s link.", "كمّل", "המשיכו", "Follow"),
    T("cta", "ask-service", "اسأل إذا {service} موجود الليلة", "שאלו אם {service} יש הערב", "Ask if {service} is on tonight", "اسأل الطبخة", "שאלו מנה", "Ask the dish", "service"),
  ],
};
