import type { NicheDefinition } from "../types";
import { T, motif } from "../warehouse";

export const tutoring: NicheDefinition = {
  id: "tutoring",
  labels: { ar: "دروس خصوصية", he: "שיעורים פרטיים", en: "Tutoring" },
  keywords: [
    "دروس",
    "درس خصوصي",
    "مدرس",
    "معلّم",
    "معلم",
    "تعزيز",
    "tutoring",
    "tutor",
    "private lesson",
    "math tutor",
    "homework",
    "בגרויות",
    "שיעורים פרטיים",
    "מורה פרטי",
    "הוראה",
    "בגרות",
    "توجيهي",
    "رياضيات",
    "انجليزي",
    "فيزياء",
  ],
  strongKeywords: ["دروس خصوصية", "שיעורים פרטיים", "توجيهي", "בגרות"],
  vetoKeywords: ["عيادة", "مطعم", "مقاول", "dental", "محامي"],
  scanPriority: ["name", "phone", "whatsapp", "services", "place", "hours"],
  ctaStyle: "whatsapp",
  serviceCatalog: [
    "رياضيات",
    "انجليزي",
    "فيزياء",
    "كيمياء",
    "توجيهي",
    "math",
    "english",
    "physics",
    "בגרות",
    "מתמטיקה",
  ],
  stockQueries: [
    "tutor desk notebook",
    "student homework table",
    "whiteboard math lesson",
    "two people studying",
    "books stack study lamp",
  ],
  motifs: [
    motif("t1", "desk", "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=900&q=80", ["desk"], "مكتب {name}", "שולחן {name}", "{name} desk"),
    motif("t2", "books", "https://images.unsplash.com/photo-1456513080880-7d93d20b90ff?w=900&q=80", ["books"], "كتب {name}", "ספרי {name}", "{name} books"),
    motif("t3", "classroom", "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=900&q=80", ["classroom"], "حصة {name}{place}", "שיעור {name}", "{name} lesson"),
    motif("t4", "notes", "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=900&q=80", ["notes"], "دفتر {name}", "מחברת {name}", "{name} notes"),
    motif("t5", "board", "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=900&q=80", ["board"], "لوح {name}", "לוח {name}", "{name} board"),
    motif("t6", "pair", "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=900&q=80", ["pair"], "حصة ثنائية — {name}", "שיעור זוגי — {name}", "pair lesson — {name}"),
    motif("t7", "write", "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=900&q=80", ["write"], "كتابة عند {name}", "כתיבה אצל {name}", "writing at {name}"),
    motif("t8", "lecture", "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=900&q=80", ["lecture"], "شرح {name}", "הסבר {name}", "{name} explanation"),
    motif("t9", "plan", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900&q=80", ["plan"], "خطة {name}", "תוכנית {name}", "{name} plan"),
  ],
  copy: [
    T("headline", "name-only", "هاي {name} — درس، مش عيادة", "זה {name} — שיעור, לא מרפאה", "This is {name} — a lesson, not a clinic", "شوف الأسلوب", "ראו סגנון", "See the style"),
    T("headline", "name-place", "درس في {place}: {name}", "שיעור ב{place}: {name}", "Lessons in {place}: {name}", "شوف وين", "איפה", "See where", "place"),
    T("headline", "pace", "شرح {service} على مهلك — {name}", "הסבר {service} בקצב שלכם — {name}", "{service} at your pace — {name}", "شوف أسلوبهم", "ראו סגנון", "See their style", "service"),
    T("headline", "service-name", "{service} مع {name}", "{service} עם {name}", "{service} with {name}", "شوف المادة", "ראו מקצוע", "See the subject", "service"),
    T("headline", "near-you", "قريب عليك في {place}: {name}", "קרוב ב{place}: {name}", "Near you in {place}: {name}", "اسأل", "שאלו", "Ask", "place"),
    T("headline", "today", "بدك حصة هالأسبوع مع {name}؟", "שיעור השבוע עם {name}?", "A lesson this week with {name}?", "يلا رتب", "יאללה", "Go"),
    T("headline", "hours", "{name} بيرد {hours}", "{name} זמין {hours}", "{name} answers {hours}", "لحّق", "תספיקו", "Catch", "hours"),
    T("headline", "question", "وينك عن درس خصوصي؟ {name} هون", "מחפשים שיעור פרטי? {name} כאן", "Need a tutor? {name} is here", "كمّل", "המשיכו", "Continue"),
    T("headline", "hello", "مركز الدرس {name}", "מרכז השיעורים {name}", "{name} tutoring desk", "أهلاً", "שלום", "Hello"),
    T("headline", "usp-service", "إذا {service} معلقك — اسأل {name}", "אם {service} תקוע — שאלו את {name}", "If {service} is stuck — ask {name}", "اسأل", "שאלו", "Ask", "service"),
    T("headline", "ready", "{name} جاهز يشرح من الأول", "{name} מוכן להסביר מההתחלה", "{name} is ready to start from the top", "احكي", "דברו", "Talk"),
    T("headline", "one-step", "خطوة وحدة لحصة {name}", "צעד אחד לשיעור {name}", "One step to a lesson with {name}", "خذ الخطوة", "צעד", "Step"),
    T("hook", "exam", "قبل الامتحان: {service} مع {name}.", "לפני המבחן: {service} עם {name}.", "Before the exam: {service} with {name}.", "رتّب الحصة", "סדרו שיעור", "Set the lesson", "service"),
    T("hook", "pain", "زهقت شرح اليوتيوب؟ {name} قدامك.", "נמאס מהסברי יוטיוב? {name} כאן.", "Tired of random videos? {name} is here.", "اسأل", "שאלו", "Ask"),
    T("hook", "neighbor", "ولد الجيران في {place} بدرس عند {name}.", "הילד של השכנים ב{place} אצל {name}.", "A neighbor’s kid in {place} studies with {name}.", "اسأل عنهم", "שאלו", "Ask around", "place"),
    T("hook", "week", "هالأسبوع فيك تحجز حصة مع {name}.", "השבוע אפשר שיעור עם {name}.", "This week you can book a lesson with {name}.", "خطّط", "תכננו", "Plan"),
    T("hook", "scroll", "وقّف السكرول: درس {name}.", "עצרו: שיעור {name}.", "Stop: tutor {name}.", "كمّل", "המשיכו", "Continue"),
    T("hook", "whatsapp", "واتساب المدرس {phone}", "וואטסאפ למורה {phone}", "WhatsApp the tutor {phone}", "ابعت", "שלחו", "Message", "phone"),
    T("hook", "call-easy", "اتّصل {phone} واسأل عن الحصص", "התקשרו {phone} על שיעורים", "Call {phone} about lessons", "اتّصل", "התקשרו", "Call", "phone"),
    T("hook", "clear", "الاسم درس: {name}.", "השם שיעור: {name}.", "The name is a tutor: {name}.", "تأكّد", "וודאו", "Confirm"),
    T("hook", "simple", "{name} — من الرابط للحصة.", "{name} — מהקישור לשיעור.", "{name} — from the link to the lesson.", "خذ الخطوة", "צעד", "Step"),
    T("hook", "direct", "بلا فورم: رتّب حصة مع {name}.", "בלי טפסים: סדרו שיעור עם {name}.", "No form: set a lesson with {name}.", "روح", "לכו", "Go"),
    T("cta", "book", "احجز حصة من صفحة {name}", "קבעו שיעור בעמוד {name}", "Book a lesson on {name}’s page", "احجز حصة", "קבעו שיעור", "Book a lesson"),
    T("cta", "call", "اتّصل {phone} واسأل عن الحصص", "התקשרו {phone} על שיעורים", "Call {phone} about lessons", "اسأل عن الحصص", "שאלו על שיעורים", "Ask about lessons", "phone"),
    T("cta", "plan", "اطلب خطة أسبوع من {name}", "בקשו תוכנית שבוע מ{name}", "Ask {name} for a weekly plan", "اطلب الخطة", "בקשו תוכנית", "Ask for a plan"),
    T("cta", "map", "العنوان في {place}", "הכתובת ב{place}", "The address in {place}", "خد الاتجاه", "ניווט", "Directions", "place"),
    T("cta", "wa", "واتساب المدرس {phone}", "וואטסאפ למורה {phone}", "WhatsApp the tutor {phone}", "واتساب الدرس", "וואטסאפ לשיעור", "WhatsApp tutor", "phone"),
    T("cta", "subject", "ابعِت إنك بدك {service}", "כתבו שאתם צריכים {service}", "Write that you need {service}", "ابعت المادة", "שלחו מקצוע", "Send the subject", "service"),
    T("cta", "visit-site", "زور صفحة {name}", "בקרו בעמוד {name}", "Visit {name}’s page", "زور", "בקרו", "Visit"),
    T("cta", "save", "احفظ مدرس {name}", "שמרו את {name}", "Save tutor {name}", "احفظ", "שמרו", "Save"),
    T("cta", "write", "اكتب الصف والمادة لـ {name}", "כתבו כיתה ומקצוע ל{name}", "Write the grade and subject to {name}", "اكتب", "כתבו", "Write"),
    T("cta", "open-now", "افتح {name} هسا", "פתחו את {name} עכשיו", "Open {name} now", "افتح", "פתחו", "Open"),
    T("hook", "hours-hook", "أوقات الحصص: {hours}.", "שעות שיעורים: {hours}.", "Lesson hours: {hours}.", "راجع", "בדקו", "Check", "hours"),
    T("hook", "no-form", "ما في لف — الحصة من رابط {name}.", "בלי סיבוב — השיעור מקישור {name}.", "No maze — the lesson is on {name}’s link.", "كمّل", "המשיכו", "Follow"),
    T("headline", "family", "احكي مع أهلك وجربوا حصة مع {name}", "דברו בבית ונסו שיעור עם {name}", "Talk at home, then try a lesson with {name}", "احكي بالبيت", "דברו בבית", "Talk at home"),
    T("hook", "who", "بتدور {service}؟ صفحة {name} إلك.", "מחפשים {service}? העמוד של {name}.", "Looking for {service}? {name}’s page.", "اختار", "בחרו", "Pick", "service"),
  ],
};
